### ISSUE TITLE
error sending proms in Midland

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1005]
On trying to send to staging proms server

```
 Starting new HTTPS connection (1): rdrf.ccgapps.com.au:443

Internal Server Error: /crc/ICHOMCRC/1/clinicalproms

Traceback (most recent call last):

File "/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen

chunked=chunked,

File "/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request

self._validate_conn(conn)

File "/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn

conn.connect()

File "/env/lib/python3.7/site-packages/urllib3/connection.py", line 394, in connect

ssl_context=context,

File "/env/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket

return context.wrap_socket(sock, server_hostname=server_hostname)

File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket

session=session

File "/usr/local/lib/python3.7/ssl.py", line 870, in _create

self.do_handshake()

File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake

self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/env/lib/python3.7/site-packages/requests/adapters.py", line 449, in send

timeout=timeout

File "/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen

method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

File "/env/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment

raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rdrf.ccgapps.com.au', port=443): Max retries exceeded with url: /cicproms/api/proms/v1/surveyassignments (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner

response = get_response(request)

File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response

response = self.process_exception_by_middleware(e, request)

File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response

response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view

return self.dispatch(request, *args, **kwargs)

File "/env/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch

return handler(request, *args, **kwargs)

File "/env/lib/python3.7/site-packages/rdrf/views/proms_views.py", line 264, in post

survey_request.send()

File "/env/lib/python3.7/site-packages/rdrf/models/proms/models.py", line 307, in send

self._send_proms_request()

File "/env/lib/python3.7/site-packages/rdrf/models/proms/models.py", line 357, in _send_proms_request

response = requests.post(api_url, data=survey_assignment_data)

File "/env/lib/python3.7/site-packages/requests/api.py", line 116, in post

return request('post', url, data=data, json=json, **kwargs)

File "/env/lib/python3.7/site-packages/requests/api.py", line 60, in request

return session.request(method=method, url=url, **kwargs)

File "/env/lib/python3.7/site-packages/requests/sessions.py", line 533, in request

resp = self.send(prep, **send_kwargs)

File "/env/lib/python3.7/site-packages/requests/sessions.py", line 646, in send

r = adapter.send(request, **kwargs)

File "/env/lib/python3.7/site-packages/requests/adapters.py", line 514, in send

raise SSLError(e, request=request)

requests.exceptions.SSLError: HTTPSConnectionPool(host='rdrf.ccgapps.com.au', port=443): Max retries exceeded with url: /cicproms/api/proms/v1/surveyassignments (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))

[ERROR:2019-10-02 15:41:06,776:log.py:228:log_response] Internal Server Error: /crc/ICHOMCRC/1/clinicalproms

Traceback (most recent call last):

File "/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen

chunked=chunked,

File "/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request

self._validate_conn(conn)

File "/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn

conn.connect()

File "/env/lib/python3.7/site-packages/urllib3/connection.py", line 394, in connect

ssl_context=context,

File "/env/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket

return context.wrap_socket(sock, server_hostname=server_hostname)

File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket

session=session

File "/usr/local/lib/python3.7/ssl.py", line 870, in _create

self.do_handshake()

File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake

self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/env/lib/python3.7/site-packages/requests/adapters.py", line 449, in send

timeout=timeout

File "/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen

method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

File "/env/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment

raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rdrf.ccgapps.com.au', port=443): Max retries exceeded with url: /cicproms/api/proms/v1/surveyassignments (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner

response = get_response(request)

File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response

response = self.process_exception_by_middleware(e, request)

File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response

response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view

return self.dispatch(request, *args, **kwargs)

File "/env/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch

return handler(request, *args, **kwargs)

File "/env/lib/python3.7/site-packages/rdrf/views/proms_views.py", line 264, in post

survey_request.send()

File "/env/lib/python3.7/site-packages/rdrf/models/proms/models.py", line 307, in send

self._send_proms_request()

File "/env/lib/python3.7/site-packages/rdrf/models/proms/models.py", line 357, in _send_proms_request

response = requests.post(api_url, data=survey_assignment_data)

File "/env/lib/python3.7/site-packages/requests/api.py", line 116, in post

return request('post', url, data=data, json=json, **kwargs)

File "/env/lib/python3.7/site-packages/requests/api.py", line 60, in request

return session.request(method=method, url=url, **kwargs)

File "/env/lib/python3.7/site-packages/requests/sessions.py", line 533, in request

resp = self.send(prep, **send_kwargs)

File "/env/lib/python3.7/site-packages/requests/sessions.py", line 646, in send

r = adapter.send(request, **kwargs)

File "/env/lib/python3.7/site-packages/requests/adapters.py", line 514, in send

raise SSLError(e, request=request)

requests.exceptions.SSLError: HTTPSConnectionPool(host='rdrf.ccgapps.com.au', port=443): Max retries exceeded with url: /cicproms/api/proms/v1/surveyassignments (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))

[pid: 38|app: 0|req: 6/125] 10.42.0.0 () {64 vars in 1381 bytes} [Wed Oct 2 15:41:06 2019] POST /crc/ICHOMCRC/1/clinicalproms => generated 21969 bytes in 338 msecs (HTTP/1.1 500) 7 headers in 244 bytes (1 switches on core 1)
```

**Comment by id2359** [comment]
The self signed certificate is the dummy cert generated by Rancher , so when we use proper certs this should go away

**Comment by id2359** [comment]
Midand fixed cert their end.
