### ISSUE TITLE
Pull proms has an error on CIC BC Staging

### ISSUE THREAD

**Issue by jithendralal** [muccg/rdrf#1403]
[ERROR:2020-06-29 15:58:49,450:proms_api.py:274:_update_proms_fields] could not locate cde PROMSConsent: ConsentQuestion matching query does not exist. | Traceback (most recent call last):
  File "/app/rdrf/rdrf/services/rest/views/proms_api.py", line 258, in _update_proms_fields
    self._update_consentvalue(patient_model, consent_question_code, value)
  File "/app/rdrf/rdrf/services/rest/views/proms_api.py", line 304, in _update_consentvalue
    consent_question_model = ConsentQuestion.objects.get(code=consent_code)
  File "/env/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
rdrf.models.definition.models.ConsentQuestion.DoesNotExist: ConsentQuestion matching query does not exist.

**Comment by gmaloneccg** [comment]
Consent appears to have been pulled correctly in all tests today.
