### ISSUE TITLE
Import fails if CustomActionExecution objects are present

### ISSUE THREAD

**Issue by jithendralal** [muccg/rdrf#1458]
Traceback (most recent call last):
  File "/env/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/env/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/env/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/app/rdrf/rdrf/management/commands/setup_proms.py", line 57, in handle
    importer.create_registry()
  File "/app/rdrf/rdrf/services/io/defs/importer.py", line 123, in create_registry
    self._create_registry_objects()
  File "/app/rdrf/rdrf/services/io/defs/importer.py", line 582, in _create_registry_objects
    self._create_custom_actions(r)
  File "/app/rdrf/rdrf/services/io/defs/importer.py", line 730, in _create_custom_actions
    CustomAction.objects.filter(registry=registry).delete()
  File "/env/lib/python3.7/site-packages/django/db/models/query.py", line 662, in delete
    collector.collect(del_query)
  File "/env/lib/python3.7/site-packages/django/db/models/deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/env/lib/python3.7/site-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'CustomAction' because they are referenced through a protected foreign key: 'CustomActionExecution.custom_action'"

**Fix:**

- [x] Add a new CharField custom_action_code to CustomActionExecution model
- [x] Make migration
- [x] apply migration
- [x] Make a data migration (to update the new field for existing instances)
- [x] apply data migration
- [x] modify list_display in CustomActionExecutionAdmin (change custom_action to custom_action_code)
- [x] Delete the protected ForeignKey from CustomActionExecution model
- [x] Make migration
- [x] apply migration

**Comment by jithendralal** [comment]
For data migration:

add an empty migration
`python manage.py makemigrations --empty rdrf`

then edit it
`
from django.db import migrations

def set_custom_action_code(apps, schema_editor):
    CustomActionExecution = apps.get_model('rdrf', 'CustomActionExecution')
    for cae in CustomActionExecution.objects.all():
        cae.custom_action_code = cae.CustomAction.code
        cae.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', **'00xx_nnnnnnnnnn'**),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
`
then migrate
