### ISSUE TITLE
Error building next_release ( prod build fails)

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1466]
```
Collecting scandir; python_version < "3.5" (from pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"->virtualenv)
  Downloading https://files.pythonhosted.org/packages/df/f5/9c052db7bd54d0cbf1bc0bb6554362bba1012d03e5888950a4f5c5dadc4e/scandir-1.10.0.tar.gz
Installing collected packages: six, contextlib2, unknown, scandir, pathlib2, unknown, importlib-metadata, appdirs, distlib, typing, singledispatch, importlib-resources, filelock, virtualenv
  Running setup.py install for unknown: started
    Running setup.py install for unknown: finished with status 'done'
  Running setup.py install for scandir: started
    Running setup.py install for scandir: finished with status 'done'
  Running setup.py install for unknown: started
    Running setup.py install for unknown: finished with status 'done'
  Running setup.py install for filelock: started
    Running setup.py install for filelock: finished with status 'done'
  Found existing installation: virtualenv 15.1.0
    DEPRECATION: Uninstalling a distutils installed project (virtualenv) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling virtualenv-15.1.0:
      Successfully uninstalled virtualenv-15.1.0
Successfully installed appdirs-1.4.4 contextlib2-0.6.0.post1 distlib-0.3.1 filelock-3.0.12 importlib-metadata-1.7.0 importlib-resources-3.0.0 pathlib2-2.3.5 scandir-1.10.0 singledispatch-3.4.0.3 six-1.15.0 typing-3.7.4.3 unknown-0.0.0 unknown-0.0.0 virtualenv-20.0.28
You are using pip version 8.1.2, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 7, in <module>
    from virtualenv.__main__ import run_with_catch
  File "/usr/lib/python2.7/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/usr/lib/python2.7/site-packages/virtualenv/run/__init__.py", line 11, in <module>
    from .plugin.activators import ActivationSelector
  File "/usr/lib/python2.7/site-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/usr/lib/python2.7/site-packages/virtualenv/run/plugin/base.py", line 9, in <module>
    from importlib_metadata import entry_points
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
ImportError: No module named zipp
ERROR: Service 'prod' failed to build: The command '/bin/sh -c pip install --upgrade virtualenv     && virtualenv $VIRTUAL_ENV     && $VIRTUAL_ENV/bin/pip install --upgrade pip==$PYTHON_PIP_VERSION' returned a non-zero code: 1
```

**Comment by id2359** [comment]
https://github.com/internetarchive/openlibrary/issues/2910
