### ISSUE TITLE
CIC Lung calculated fields error

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1471]
Occurs when there is no clinical data saved  ( all or form not sure)

**Comment by jithendralal** [comment]
The management command update_calculated_fields gets interrupted due to an error.

**Comment by id2359** [comment]
```
ccg-user@rdrf-ciclung:~$ django-admin update_calculated_fields
[INFO:2020-08-03 11:52:49,822:apps.py:14:ready] running RDRFConfig.ready ... 
[ERROR:2020-08-03 11:52:50,815:utils.py:35:func_wrapper] 'patient_id' | Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/rdrf/helpers/utils.py", line 30, in func_wrapper
    return func(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/rdrf/management/commands/update_calculated_fields.py", line 110, in handle
    new_calculated_cde_value = calculate_cde(patient_model, form_cde_values, calculated_cde_model)
  File "/env/lib/python3.7/site-packages/rdrf/management/commands/update_calculated_fields.py", line 161, in calculate_cde
    return func(patient_values, form_values)
  File "/env/lib/python3.7/site-packages/rdrf/forms/fields/calculated_functions.py", line 917, in DXINTERVALLC
    'FIRSTSEENLC')
  File "/env/lib/python3.7/site-packages/rdrf/forms/fields/calculated_functions.py", line 873, in date_diff_helper
    patient_id = patient["patient_id"]
KeyError: 'patient_id'

Traceback (most recent call last):
  File "/env/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/env/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/env/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/env/lib/python3.7/site-packages/rdrf/helpers/utils.py", line 36, in func_wrapper
    raise e
  File "/env/lib/python3.7/site-packages/rdrf/helpers/utils.py", line 30, in func_wrapper
    return func(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/rdrf/management/commands/update_calculated_fields.py", line 110, in handle
    new_calculated_cde_value = calculate_cde(patient_model, form_cde_values, calculated_cde_model)
  File "/env/lib/python3.7/site-packages/rdrf/management/commands/update_calculated_fields.py", line 161, in calculate_cde
    return func(patient_values, form_values)
  File "/env/lib/python3.7/site-packages/rdrf/forms/fields/calculated_functions.py", line 917, in DXINTERVALLC
    'FIRSTSEENLC')
  File "/env/lib/python3.7/site-packages/rdrf/forms/fields/calculated_functions.py", line 873, in date_diff_helper
    patient_id = patient["patient_id"]
KeyError: 'patient_id'
ccg-user@rdrf-ciclung:~$ 
```

**Comment by gmaloneccg** [comment]
Logged in as a clinical staff user, when data are missing for the required fields for calculation, there does not appear to be an error or any other problematic behaviour on staging.
