### ISSUE TITLE
RDRF: Django-admin init command traceback

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1611]
When shelling into the Docker container for a local RDRF application (dev/prod), running `django-admin init DEV` to create default users and settings causes the following traceback to occur after "Loading genes_smaller_sample...":
```Traceback (most recent call last):
  File "/env/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/env/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/env/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/env/lib/python3.8/site-packages/rdrf/management/commands/init.py", line 33, in handle
    self.load_module_data(name, **options)
  File "/env/lib/python3.8/site-packages/rdrf/management/commands/init.py", line 45, in load_module_data
    self.load_module_data(dep, **options)
  File "/env/lib/python3.8/site-packages/rdrf/management/commands/init.py", line 47, in load_module_data
    self.load_data_once(module, **options)
  File "/env/lib/python3.8/site-packages/rdrf/management/commands/init.py", line 53, in load_data_once
    module.load_data(**options)
  File "/env/lib/python3.8/site-packages/rdrf/initial_data/genes_smaller_sample.py", line 14, in load_data
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/env/lib/python3.8/site-packages/rdrf/initial_data/genes_smaller_sample.json'```

**Comment by id2359** [comment]
Closing stale issue
