### ISSUE TITLE
React Warning

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1787]
- [x] What causes this?
  - Anything that does not meet the DOM requirements of `react-dom` is logged by validateDOMNesting
- [x] Can we fix it?
  - Yes, we can fix up anything causing the warnings without affecting the operations of the frontend (see commit fffbd58)
- [x] Can we make the output of this look like a warning?
  - No, but the warnings can be disabled by adding `/* eslint-disable */` to the top of the files the warnings are produced in (see issue 2070 for create-react-app)
- [ ] Why is our code working anyway?

Output is unnerving when I look at Travis build log ( looks like a stacktrace or error):

console.error
      Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
          in p (at question.tsx:355)
          in p (at question.tsx:354)
          in div (at question.tsx:353)
          in div (at question.tsx:352)
          in div (at question.tsx:351)
          in div (created by FormGroup)
          in FormGroup (at question.tsx:350)
          in form (created by Form)
          in Form (at question.tsx:342)
          in Question (created by ConnectFunction)
          in ConnectFunction (at app/index.tsx:155)
          in div (created by Col)
          in Col (at app/index.tsx:154)
          in div (created by Row)
          in Row (at app/index.tsx:153)
          in div (at app/index.tsx:146)
          in div (created by Container)
          in Container (at app/index.tsx:145)
          in div (at app/index.tsx:144)
          in App (created by ConnectFunction)
          in ConnectFunction (at app.unit.test.tsx:3311)
          in Provider (at app.unit.test.tsx:3310)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at validateDOMNesting (node_modules/react-dom/cjs/react-dom.development.js:7383:7)
      at createInstance (node_modules/react-dom/cjs/react-dom.development.js:7479:5)
      at completeWork (node_modules/react-dom/cjs/react-dom.development.js:18970:28)
      at completeUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22189:16)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22165:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22130:22)

**Comment by id2359** [comment]
These are warnings writing to console.error - they don;t break the build and the react functionality is working.

But we must be doing something bad to get these.
