### ISSUE TITLE
Celery error : Module not found click._bashcomplete

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1796]
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/env/bin/celery", line 8, in <module>
celeryworker_1  |     sys.exit(main())
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/__main__.py", line 14, in main
celeryworker_1  |     from celery.bin.celery import main as _main
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/bin/celery.py", line 12, in <module>
celeryworker_1  |     from celery.bin.amqp import amqp
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/bin/amqp.py", line 7, in <module>
celeryworker_1  |     from click_repl import register_repl
celeryworker_1  |   File "/env/lib/python3.8/site-packages/click_repl/__init__.py", line 6, in <module>
celeryworker_1  |     import click._bashcomplete
celeryworker_1  | ModuleNotFoundError: No module named 'click._bashcomplete'

**Comment by id2359** [comment]
This was raised as  a ticket in celery - looks like this version fixes it.
