### ISSUE TITLE
Bootstrap 5: Progress bar not displaying percentage completion

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1813]
This issue relates to #1774.

When running Aloe tests with Bootstrap 5.0.0 installed, the following failure occurs:
```
FAIL: Curator edits multisection (features.dd_edit_diagnosis: Edit diagnosis for a patient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/aloe/registry.py", line 151, in wrapped
    return function(*args, **kwargs)
  File "/app/rdrf/rdrf/testing/behaviour/features/dd_edit_diagnosis.feature", line 54, in Curator edits multisection
    Then the progress indicator should be "0%"
  File "/env/lib/python3.8/site-packages/aloe/registry.py", line 151, in wrapped
    return function(*args, **kwargs)
  File "/app/rdrf/rdrf/testing/behaviour/features/steps.py", line 552, in the_progress_indicator_should_be
    assert_equal(progress_bar.text.strip(), percentage)
AssertionError: '' != '0%'
+ 0%
```

When checking the progress bar using VNC Viewer on the running test container during the above test, the bar does not display any text - normally "0%" will be shown.

**Comment by APMCCG** [comment]
Fixed minor display issue with progress bar, but real issue was with Selenium - the step `the_progress_indicator_should_be` was no longer correctly selecting the innerText property. Once the selected property was changed to innerHTML, the step behaved normally.
