### ISSUE TITLE
Bootstrap 5: CDE history widget not displaying

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1814]
This issue relates to #1774.

When running Aloe tests with Bootstrap 5.0.0 installed, the following error occurs:
```
ERROR: Enter successive values for a field (features.fh_history_widget: Sanity test history widget.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/aloe/registry.py", line 151, in wrapped
    return function(*args, **kwargs)
  File "/app/rdrf/rdrf/testing/behaviour/features/fh_history_widget.feature", line 28, in Enter successive values for a field
    And History for form "Medications" section "Hypertensive Medication" cde "If other, enter medication name(s)" shows "foo,foobar,foobarbaz"
  File "/env/lib/python3.8/site-packages/aloe/registry.py", line 151, in wrapped
    return function(*args, **kwargs)
  File "/app/rdrf/rdrf/testing/behaviour/features/steps.py", line 693, in check_history_popup
    WebDriverWait(world.browser, 60).until(
  File "/env/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

When clicking on the history button next to a CDE in a local build, the history widget fails to display, but the element is created in the page (observed in source window of browser developer tools). If the button is clicked multiple times, multiple elements are created.

**Comment by APMCCG** [comment]
The modal is successfully being created by the Bootstrap JS code regardless of whether JQuery or standard JS is used to create it. However, the `show.bs.modal` event used to activate the component is either not being fired or is not being caught and handled properly.
