### ISSUE TITLE
error showing in HSS CIC proms logs

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1913]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./uwsgi/django.wsgi", line 11, in application
    return get_wsgi_application()(environ,start)
  File "/env/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/env/lib/python3.8/site-packages/rdrf/urls.py", line 67, in handler500
    return render(request, "500.html")
  File "/env/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/env/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/env/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/env/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/env/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/env/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/env/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/env/lib/python3.8/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'javascript-catalog' not found. 'javascript-catalog' is not a valid view function or pattern name.
[pid: 34|app: 0|req: 8/24] 172.16.79.2 () {60 vars in 1456 bytes} [Wed Aug  4 11:32:57 2021] GET /crc/promslanding?t=446fce2b-e392-4417-8670-b8e42c241cfc&r=ICHOMCRC&s=BaselinePROMS => generated 0 bytes in 19559 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)

**Comment by id2359** [comment]
Might be  dupe?
