### ISSUE TITLE
not seeing celery container logs in hss uat

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2075]
the registry.log was empty
but when I ran docker logs crc-worker , I could see there were logger messages

**Comment by id2359** [comment]
seeiing ccg-user@crc-worker:~/log$ cat registry.log
[ERROR:2021-03-16 11:41:02,167:signal.py:280:send] Signal handler <bound method DjangoFixup.on_worker_init of <celery.fixups.django.DjangoFixup object at 0x7fc3f9e36070>> raised: ValueError('Unable to parse connection string: ""memcached:11211""')
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/env/lib/python3.8/site-packages/celery/fixups/django.py", line 85, in on_worker_init
    self.worker_fixup.install()
  File "/env/lib/python3.8/site-packages/celery/fixups/django.py", line 130, in install
    self.close_cache()
  File "/env/lib/python3.8/site-packages/celery/fixups/django.py", line 197, in close_cache
    self._cache.close_caches()
  File "/env/lib/python3.8/site-packages/django/core/cache/__init__.py", line 121, in close_caches
    cache.close()
  File "/env/lib/python3.8/site-packages/django/core/cache/backends/memcached.py", line 101, in close
    self._cache.disconnect_all()
  File "/env/lib/python3.8/site-packages/django/core/cache/backends/memcached.py", line 174, in _cache
    self._client = self._lib.Client(self._servers, **client_kwargs)
  File "/env/lib/python3.8/site-packages/memcache.py", line 215, in __init__
    self.set_servers(servers)
  File "/env/lib/python3.8/site-packages/memcache.py", line 291, in set_servers
    self.servers = [_Host(s, self.debug, dead_retry=self.dead_retry,
  File "/env/lib/python3.8/site-packages/memcache.py", line 291, in <listcomp>
    self.servers = [_Host(s, self.debug, dead_retry=self.dead_retry,
  File "/env/lib/python3.8/site-packages/memcache.py", line 1347, in __init__
    raise ValueError('Unable to parse connection string: "%s"' % host)
ValueError: Unable to parse connection string: ""memcached:11211""

**Comment by id2359** [comment]
I think this is caused by (lack of) logger config than the runtime error above
