### ISSUE TITLE
prod build error - svglib

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2160]
Seeing this in Travis:

Collecting svglib>=1.2.1
  Downloading svglib-1.2.1.tar.gz (896 kB)
     |████████████████████████████████| 896 kB 38.0 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jft0a2ng/svglib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jft0a2ng/svglib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wsnmjg8q
         cwd: /tmp/pip-install-jft0a2ng/svglib/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jft0a2ng/svglib/setup.py", line 10, in <module>
        setup(
      File "/env/lib/python3.8/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/env/lib/python3.8/site-packages/setuptools/__init__.py", line 121, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/env/lib/python3.8/site-packages/setuptools/dist.py", line 433, in parse_config_files
        parse_configuration(self, self.command_options,
      File "/env/lib/python3.8/site-packages/setuptools/config.py", line 110, in parse_configuration
        options.parse()
      File "/env/lib/python3.8/site-packages/setuptools/config.py", line 378, in parse
        raise DistutilsOptionError(
    distutils.errors.DistutilsOptionError: Unsupported distribution option section: [options.data_files]
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by id2359** [comment]
svglib must be an added dependancy from last good next release build

**Comment by id2359** [comment]
I issued a rebuild on master in Travis and the build fails now ( it passed last week.) This suggests some transitive dependency updated.

**Comment by id2359** [comment]
Must be html2pdf which wasn't pinned 0.2.5 doesn't have svglib as a dep (https://github.com/xhtml2pdf/xhtml2pdf/blob/v0.2.5/setup.py) , but the latest html2pdf 0.2.6 introduced this dep ( https://github.com/xhtml2pdf/xhtml2pdf/blob/v0.2.6/setup.py) which breaks the build.
Pinning html2pdf to 0.2.5 for now.

**Comment by id2359** [comment]
forgot to tag ticket https://github.com/muccg/rdrf/commit/d74ee4d36de938e2b4918e6dcb09eee8ca44c860
