### ISSUE TITLE
Review frontend deps

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2176]
"@types/jest": "25.1.4",
    "@types/lodash": "^4.14.149",
    "@types/node": "13.9.0",
    "@types/rc-slider": "^8.6.5",
    "@types/rc-tooltip": "^3.7.2",
    "@types/react": "16.9.23",
    "@types/react-dom": "16.9.5",
    "@types/react-redux": "^7.1.7",
    "@types/reactstrap": "^8.4.2",
    "@types/redux-actions": "^2.6.1",
    "axios": "^0.21.2",
    "bootstrap": "^4.4.1",
    "child_process": "^1.0.2",
    "lodash": "^4.17.19",
    "npm-watch": "^0.9.0",
    "rc-slider": "^9.2.2",
    "rc-tooltip": "^4.0.1",
    "react": "^16.13.0",
    "react-device-detect": "^1.11.14",
    "react-dom": "^16.13.0",
    "react-icons": "^3.9.0",
    "react-redux": "^7.2.0",
    "react-scripts": "4.0.3",
    "reactstrap": "^8.4.1",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.5",
    "redux-thunk": "^2.3.0",
    "typescript": "3.8.3",
    "yarn": "^1.22.4"

**Comment by id2359** [comment]
Upgrading to React 18:

All the tests fail to execute because the root element isn't loaded properly , yet the build passes .. I think the errors are actually warnings which don't fail the build

**Comment by id2359** [comment]
https://stackoverflow.com/questions/71685441/react-testing-library-gives-console-error-for-reactdom-render-in-react-18

**Comment by id2359** [comment]
ran 

yarn add --dev @testing-library/react@latest
yarn add --dev @testing-library/jest-dom@latest
yarn add --dev @testing-library/user-event@latest
inside node container

**Comment by id2359** [comment]
Local tests pass ( surprisingly )

**Comment by id2359** [comment]
I updated to

 "dependencies": {
    "@types/jest": "25.1.4",
    "@types/lodash": "^4.14.149",
    "@types/node": "13.9.0",
    "@types/rc-slider": "^8.6.5",
    "@types/rc-tooltip": "^3.7.2",
    "@types/react": "18.0.8",
    "@types/react-dom": "18.0.3",
    "@types/react-redux": "^7.1.7",
    "@types/reactstrap": "^8.4.2",
    "@types/redux-actions": "^2.6.1",
    "axios": "^0.27.2",
    "bootstrap": "^4.4.1",
    "child_process": "^1.0.2",
    "lodash": "^4.17.21",
    "npm-watch": "^0.11.0",
    "rc-slider": "^9.2.2",
    "rc-tooltip": "^4.0.1",
    "react": "^18.1.0",
    "react-device-detect": "^2.2.2",
    "react-dom": "^18.1.0",
    "react-icons": "^4.3.1",
    "react-redux": "^8.0.1",
    "react-scripts": "5.0.1",
    "reactstrap": "^8.4.1",
    "redux": "^4.2.0",
    "redux-actions": "^2.6.5",
    "redux-thunk": "^2.4.1",
    "typescript": "4.6.4",
    "yarn": "^1.22.18"

**Comment by id2359** [comment]
The tests are failing again but the build passes

this time:

warning "@types/reactstrap > reactstrap > react-popper@1.3.11" has incorrect peer dependency "react@0.14.x || ^15.0.0 || ^16.0.0 || ^17.0.0".
warning " > bootstrap@4.6.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.6.0" has unmet peer dependency "popper.js@^1.16.1".
warning "rc-tooltip > rc-trigger > rc-motion@1.1.2" has incorrect peer dependency "react@^16.0.0".
warning "rc-tooltip > rc-trigger > rc-motion@1.1.2" has incorrect peer dependency "react-dom@^16.0.0".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning " > @testing-library/user-event@14.1.1" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > tslint-react@4.2.0" has incorrect peer dependency "tslint@^5.1.0".
[4/4] Building fresh packages...
> cicproms@2.0.0 test
> react-scripts test
PASS src/app/app.unit.test.tsx (7.755 s)
  ● Console
    console.error
      Warning: An update to Connect(App) inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at ConnectFunction (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/connect.js:241:87)
          at Provider (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/Provider.js:19:3)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27543:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25404:5)
      at forceStoreRerender (node_modules/react-dom/cjs/react-dom.development.js:16844:3)
      at handleStoreChange (node_modules/react-dom/cjs/react-dom.development.js:16823:7)
      at Object.checkForUpdates [as onStateChange] (node_modules/react-redux/lib/components/connect.js:132:7)
      at Object.handleChangeWrapper [as callback] (node_modules/react-redux/lib/utils/Subscription.js:97:20)
    console.error
      Warning: An update to Connect(App) inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at ConnectFunction (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/connect.js:241:87)
          at Provider (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/Provider.js:19:3)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27543:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25404:5)
      at forceStoreRerender (node_modules/react-dom/cjs/react-dom.development.js:16844:3)
      at handleStoreChange (node_modules/react-dom/cjs/react-dom.development.js:16823:7)
      at Object.checkForUpdates [as onStateChange] (node_modules/react-redux/lib/components/connect.js:132:7)
      at Object.handleChangeWrapper [as callback] (node_modules/react-redux/lib/utils/Subscription.js:97:20)
    console.error
      Warning: An update to Connect(App) inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at ConnectFunction (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/connect.js:241:87)
          at Provider (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/Provider.js:19:3)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27543:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25404:5)
      at forceStoreRerender (node_modules/react-dom/cjs/react-dom.development.js:16844:3)
      at handleStoreChange (node_modules/react-dom/cjs/react-dom.development.js:16823:7)
      at Object.checkForUpdates [as onStateChange] (node_modules/react-redux/lib/components/connect.js:132:7)
      at Object.handleChangeWrapper [as callback] (node_modules/react-redux/lib/utils/Subscription.js:97:20)
    console.error
      Warning: An update to Connect(App) inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at ConnectFunction (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/connect.js:241:87)
          at Provider (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/Provider.js:19:3)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27543:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25404:5)
      at forceStoreRerender (node_modules/react-dom/cjs/react-dom.development.js:16844:3)
      at handleStoreChange (node_modules/react-dom/cjs/react-dom.development.js:16823:7)
      at Object.checkForUpdates [as onStateChange] (node_modules/react-redux/lib/components/connect.js:132:7)
      at Object.handleChangeWrapper [as callback] (node_modules/react-redux/lib/utils/Subscription.js:97:20)
    console.error
      Warning: An update to Connect(App) inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at ConnectFunction (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/connect.js:241:87)
          at Provider (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/Provider.js:19:3)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27543:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25404:5)
      at forceStoreRerender (node_modules/react-dom/cjs/react-dom.development.js:16844:3)
      at handleStoreChange (node_modules/react-dom/cjs/react-dom.development.js:16823:7)
      at Object.checkForUpdates [as onStateChange] (node_modules/react-redux/lib/components/connect.js:132:7)
      at Object.handleChangeWrapper [as callback] (node_modules/react-redux/lib/utils/Subscription.js:97:20)
PASS src/pages/proms_page/components/question.unit.test.tsx
Test Suites: 2 passed, 2 total
Tests:       92 passed, 92 total
Snapshots:   1 passed, 1 total
Time:        8.786 s
Ran all test suites.
  [INFO] run docker-compose.yml
  [INFO] GIT_BRANCH: upgrade-frontend
  [INFO] GIT_HEAD_TAG: 
  [INFO] GIT_LATEST_TAG: 
  [INFO] No git tag set, using branch name
  [ OK ] BUILD_VERSION: upgrade-frontend
+ exec docker-compose --project-name rdrf -f docker-compose.yml run --rm node lint
Starting rdrf_datadev_1 ... 
HOSTNAME=ab873b12664f
NODE_VERSION=16.15.0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/app/rdrf/rdrf/frontend
SHLVL=0
TERM=xterm
YARN_CACHE_FOLDER=/opt/yarn_cache
YARN_VERSION=1.22.18
_=/usr/bin/env
  [INFO] [Run] Lint the JS code
yarn install v1.22.18
[1/4] Resolving packages...
success Already up-to-date.
> cicproms@2.0.0 lint
> tslint 'src/**/*.ts{,x}'
The command "./travis-build.sh || travis_terminate 1;" exited with 0.
0.01s$ ./travis-prodbuild.sh || travis_terminate 1;
Branch upgrade-frontend is not deployable. Skipping prod build and tests
The command "./travis-prodbuild.sh || travis_terminate 1;" exited with 0.
Done. Your build exited with 0.

**Comment by id2359** [comment]
See https://stackoverflow.com/questions/56722139/when-testing-code-that-causes-react-state-updates-should-be-wrapped-into-act

**Comment by id2359** [comment]
warning "@types/reactstrap > reactstrap > react-popper@1.3.11" has incorrect peer dependency "react@0.14.x || ^15.0.0 || ^16.0.0 || ^17.0.0".
warning " > bootstrap@4.6.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.6.0" has unmet peer dependency "popper.js@^1.16.1".
warning "rc-tooltip > rc-trigger > rc-motion@1.1.2" has incorrect peer dependency "react@^16.0.0".
warning "rc-tooltip > rc-trigger > rc-motion@1.1.2" has incorrect peer dependency "react-dom@^16.0.0".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning " > @testing-library/user-event@14.1.1" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > tslint-react@4.2.0" has incorrect peer dependency "tslint@^5.1.0".

**Comment by id2359** [comment]
> cicproms@2.0.0 test
> react-scripts test
PASS src/app/app.unit.test.tsx (7.755 s)
  ● Console
    console.error
      Warning: An update to Connect(App) inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at ConnectFunction (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/connect.js:241:87)
          at Provider (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/Provider.js:19:3)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27543:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25404:5)
      at forceStoreRerender (node_modules/react-dom/cjs/react-dom.development.js:16844:3)
      at handleStoreChange (node_modules/react-dom/cjs/react-dom.development.js:16823:7)
      at Object.checkForUpdates [as onStateChange] (node_modules/react-redux/lib/components/connect.js:132:7)
      at Object.handleChangeWrapper [as callback] (node_modules/react-redux/lib/utils/Subscription.js:97:20)
    console.error
      Warning: An update to Connect(App) inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at ConnectFunction (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/connect.js:241:87)
          at Provider (/app/rdrf/rdrf/frontend/node_modules/react-redux/lib/components/Provider.js:19:3)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27543:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25404:5)
      at forceStoreRerender (node_modules/react-dom/cjs/react-dom.development.js:16844:3)
      at handleStoreChange (node_modules/react-dom/cjs/react-dom.development.js:16823:7)
      at Object.checkForUpdates [as onStateChange] (node_modules/react-redux/lib/components/connect.js:132:7)
      at Object.handleChangeWrapper [as callback] (node_modules/react-redux/lib/utils/Subscription.js:97:20)

**Comment by id2359** [comment]
Turned out to be testStore.dispatch calls in the tests , which had to be wrapped in act(() => {}) calls.

I parsed the file using Rebol and updated via a parse rule which saved a lot of time.

**Comment by id2359** [comment]
Also added types for moxios
