### ISSUE TITLE
next_release build error

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2206]
Collecting svglib>=1.2.1
  Downloading svglib-1.4.1.tar.gz (913 kB)
     |████████████████████████████████| 913 kB 49.2 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bh7l65ig/svglib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bh7l65ig/svglib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xsle89gm
         cwd: /tmp/pip-install-bh7l65ig/svglib/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bh7l65ig/svglib/setup.py", line 10, in <module>
        setup(
      File "/env/lib/python3.8/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/env/lib/python3.8/site-packages/setuptools/__init__.py", line 121, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/env/lib/python3.8/site-packages/setuptools/dist.py", line 433, in parse_config_files
        parse_configuration(self, self.command_options,
      File "/env/lib/python3.8/site-packages/setuptools/config.py", line 110, in parse_configuration
        options.parse()
      File "/env/lib/python3.8/site-packages/setuptools/config.py", line 378, in parse
        raise DistutilsOptionError(
    distutils.errors.DistutilsOptionError: Unsupported distribution option section: [options.data_files]
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by id2359** [comment]
According to the internet, "options.data_files only became supported in setuptools 40.5.0."

Collecting svglib>=1.2.1
Downloading svglib-1.4.1.tar.gz (913 kB) 

must use this , but we're using an earlier version of setuptools

**Comment by id2359** [comment]
setuptools is defined in the base image ..

**Comment by id2359** [comment]
https://app.travis-ci.com/github/muccg/rdrf/builds/254655794 


By the time we start building a release tarball:


_=/usr/bin/env
  [INFO] [Run] Preparing a release tarball
  [INFO] BUILD_VERSION next_release
  [INFO] PROJECT_SOURCE https://github.com/muccg/rdrf.git
Collecting setuptools<=37.0.0,>=36.0.0
  Downloading setuptools-37.0.0-py2.py3-none-any.whl (481 kB)
     |████████████████████████████████| 481 kB 3.9 MB/s 
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.2.0
    Uninstalling setuptools-65.2.0:
      Successfully uninstalled setuptools-65.2.0
Successfully installed setuptools-37.0.0


Some dep is constraining setup tools which gets reverted to an earlier version which causes a build failure during svglib

**Comment by id2359** [comment]
docker-entrypoint-build was artificially restricting setuptools to an incompatible(now) version.
