### ISSUE TITLE
HSS Prod BC HL7 ADT_A01 error  Object of type AssertionError is not JSON serializable

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2230]
[INFO:2022-09-15 10:13:27,637:tasks.py:45:handle_hl7_message] HL7 handler: XXX ADT_A01 received
[INFO:2022-09-15 10:13:27,637:updater.py:192:handle] updating or creating patient from hl7 message data
[INFO:2022-09-15 10:13:27,699:utils.py:46:get_event_code] get event code 
[INFO:2022-09-15 10:13:27,699:utils.py:51:get_event_code] event code = ADT_A01
[INFO:2022-09-15 10:13:27,699:utils.py:46:get_event_code] get event code 
[INFO:2022-09-15 10:13:27,699:utils.py:51:get_event_code] event code = ADT_A01
[ERROR:2022-09-15 10:13:27,700:updater.py:234:handle] Error creating/updating patient None: 
[INFO:2022-09-15 10:13:27,700:tasks.py:49:handle_hl7_message] HL7 handler: K7399621 ADT_A01 processed
[ERROR:2022-09-15 10:13:27,702:trace.py:265:_log_error] Task rdrf.services.tasks.handle_hl7_message[c8700604-8cec-4015-9d1e-23791e7d2848] raised unexpected: EncodeError(TypeError('Object of type AssertionError is not JSON serializable'))
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 49, in _reraise_errors
    yield
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 65, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 55, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AssertionError is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/celery/app/trace.py", line 517, in trace_task
    mark_as_done(
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 161, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 477, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 904, in _store_result
    self._set_with_state(self.get_key_for_task(task_id), self.encode(meta), state)
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 367, in encode
    _, _, payload = self._encode(data)
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 371, in _encode
    return dumps(data, serializer=self.serializer)
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 53, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/env/lib/python3.8/site-packages/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 49, in _reraise_errors
    yield
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 65, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 55, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type AssertionError is not JSON serializable

**Comment by id2359** [comment]
In redis

 get "celery-task-meta-efafa5d2-dace-4c90-8985-3166ee8af8cb"
"{\"status\": \"FAILURE\", \"result\": {\"exc_type\": \"EncodeError\", \"exc_message\": [\"TypeError('Object of type AssertionError is not JSON serializable')\"], \"exc_module\": \"kombu.exceptions\"}, \"traceback\": \"Traceback (most recent call last):\\n  File \\\"/env/lib/python3.8/site-packages/kombu/serialization.py\\\", line 49, in _reraise_errors\\n    yield\\n  File \\\"/env/lib/python3.8/site-packages/kombu/serialization.py\\\", line 220, in dumps\\n    payload = encoder(data)\\n  File \\\"/env/lib/python3.8/site-packages/kombu/utils/json.py\\\", line 65, in dumps\\n    return _dumps(s, cls=cls or _default_encoder,\\n  File \\\"/usr/local/lib/python3.8/json/__init__.py\\\", line 234, in dumps\\n    return cls(\\n  File \\\"/usr/local/lib/python3.8/json/encoder.py\\\", line 199, in encode\\n    chunks = self.iterencode(o, _one_shot=True)\\n  File \\\"/usr/local/lib/python3.8/json/encoder.py\\\", line 257, in iterencode\\n    return _iterencode(o, 0)\\n  File \\\"/env/lib/python3.8/site-packages/kombu/utils/json.py\\\", line 55, in default\\n    return super().default(o)\\n  File \\\"/usr/local/lib/python3.8/json/encoder.py\\\", line 179, in default\\n    raise TypeError(f'Object of type {o.__class__.__name__} '\\nTypeError: Object of type AssertionError is not JSON serializable\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/env/lib/python3.8/site-packages/celery/app/trace.py\\\", line 517, in trace_task\\n    mark_as_done(\\n  File \\\"/env/lib/python3.8/site-packages/celery/backends/base.py\\\", line 161, in mark_as_done\\n    self.store_result(task_id, result, state, request=request)\\n  File \\\"/env/lib/python3.8/site-packages/celery/backends/base.py\\\", line 477, in store_result\\n    self._store_result(task_id, result, state, traceback,\\n  File \\\"/env/lib/python3.8/site-packages/celery/backends/base.py\\\", line 904, in _store_result\\n    self._set_with_state(self.get_key_for_task(task_id), self.encode(meta), state)\\n  File \\\"/env/lib/python3.8/site-packages/celery/backends/base.py\\\", line 367, in encode\\n    _, _, payload = self._encode(data)\\n  File \\\"/env/lib/python3.8/site-packages/celery/backends/base.py\\\", line 371, in _encode\\n    return dumps(data, serializer=self.serializer)\\n  File \\\"/env/lib/python3.8/site-packages/kombu/serialization.py\\\", line 220, in dumps\\n    payload = encoder(data)\\n  File \\\"/usr/local/lib/python3.8/contextlib.py\\\", line 131, in __exit__\\n    self.gen.throw(type, value, traceback)\\n  File \\\"/env/lib/python3.8/site-packages/kombu/serialization.py\\\", line 53, in _reraise_errors\\n    reraise(wrapper, wrapper(exc), sys.exc_info()[2])\\n  File \\\"/env/lib/python3.8/site-packages/kombu/exceptions.py\\\", line 21, in reraise\\n    raise value.with_traceback(tb)\\n  File \\\"/env/lib/python3.8/site-packages/kombu/serialization.py\\\", line 49, in _reraise_errors\\n    yield\\n  File \\\"/env/lib/python3.8/site-packages/kombu/serialization.py\\\", line 220, in dumps\\n    payload = encoder(data)\\n  File \\\"/env/lib/python3.8/site-packages/kombu/utils/json.py\\\", line 65, in dumps\\n    return _dumps(s, cls=cls or _default_encoder,\\n  File \\\"/usr/local/lib/python3.8/json/__init__.py\\\", line 234, in dumps\\n    return cls(\\n  File \\\"/usr/local/lib/python3.8/json/encoder.py\\\", line 199, in encode\\n    chunks = self.iterencode(o, _one_shot=True)\\n  File \\\"/usr/local/lib/python3.8/json/encoder.py\\\", line 257, in iterencode\\n    return _iterencode(o, 0)\\n  File \\\"/env/lib/python3.8/site-packages/kombu/utils/json.py\\\", line 55, in default\\n    return super().default(o)\\n  File \\\"/usr/local/lib/python3.8/json/encoder.py\\\", line 179, in default\\n    raise TypeError(f'Object of type {o.__class__.__name__} '\\nkombu.exceptions.EncodeError: Object of type AssertionError is not JSON serializable\\n\", \"children\": [], \"date_done\": \"2022-09-15T04:01:33.847575\", \"task_id\": \"efafa5d2-dace-4c90-8985-3166ee8af8cb\"}"

**Comment by id2359** [comment]
[INFO:2022-09-15 10:13:27,636:tasks.py:39:handle_hl7_message] processing task for umrn PATIENTUMRN
[INFO:2022-09-15 10:13:27,636:utils.py:46:get_event_code] get event code 
[INFO:2022-09-15 10:13:27,637:utils.py:51:get_event_code] event code = ADT_A01
[INFO:2022-09-15 10:13:27,637:tasks.py:45:handle_hl7_message] HL7 handler: PATIENTUMRN ADT_A01 received
[INFO:2022-09-15 10:13:27,637:updater.py:192:handle] updating or creating patient from hl7 message data
[INFO:2022-09-15 10:13:27,699:utils.py:46:get_event_code] get event code 
[INFO:2022-09-15 10:13:27,699:utils.py:51:get_event_code] event code = ADT_A01
[INFO:2022-09-15 10:13:27,699:utils.py:46:get_event_code] get event code 
[INFO:2022-09-15 10:13:27,699:utils.py:51:get_event_code] event code = ADT_A01
[ERROR:2022-09-15 10:13:27,700:updater.py:234:handle] Error creating/updating patient None: 
[INFO:2022-09-15 10:13:27,700:tasks.py:49:handle_hl7_message] HL7 handler: PATIENTUMRN ADT_A01 processed
[ERROR:2022-09-15 10:13:27,702:trace.py:265:_log_error] Task rdrf.services.tasks.handle_hl7_message[c8700604-8cec-4015-9d1e-23791e7d2848] raised unexpected: EncodeError(TypeError('Object of type AssertionError is not JSON serializable'))
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 49, in _reraise_errors
    yield
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 65, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 55, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AssertionError is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/celery/app/trace.py", line 517, in trace_task
    mark_as_done(
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 161, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 477, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 904, in _store_result
    self._set_with_state(self.get_key_for_task(task_id), self.encode(meta), state)
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 367, in encode
    _, _, payload = self._encode(data)
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 371, in _encode
    return dumps(data, serializer=self.serializer)
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 53, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/env/lib/python3.8/site-packages/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 49, in _reraise_errors
    yield
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 65, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 55, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
