### ISSUE TITLE
Additional rules for clinical cancer stage LC and CRC

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2246]
Hi Lee,

If you have time before you upload the new versions of lung and colorectal to UAT.

Could add an additional stage  called  STAGE IV

 

- [x] For lung cancer

Stage IV

TNMCTLC = cT* TNMCNLC = cN* TNMCMLC = cM1 (*any T and any N value including unknown)

NB: Invalid won't fix - Email 101022 from AI 11:45am saying this was a mistake ( I'd pointed out a) we have no c values and b) only M1a M1b M1c not M1 )

- [x] For crc

Stage IV

TNMCTCRC = cT* TNMCNCRC = cN* TNMCMCRC = cM1 (*any T and any N value including unknown)

 

Thanks Angela

**Comment by id2359** [comment]
Build failed after LC change with:

======================================================================
ERROR [5.891s]: test_lc_clinical_cancer_stage (rdrf.testing.unit.tests.CICCancerStageTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/rdrf/rdrf/testing/unit/tests.py", line 2989, in test_lc_clinical_cancer_stage
    evaluator = evaluator_class(spec=spec, cde_prefix="TNMC")
  File "/app/rdrf/rdrf/forms/fields/calculated_functions.py", line 871, in __init__
    self.rules_dict = self.parse_spec(spec)
  File "/app/rdrf/rdrf/forms/fields/calculated_functions.py", line 963, in parse_spec
    dicts = self.parse_spec_inputs(line)
  File "/app/rdrf/rdrf/forms/fields/calculated_functions.py", line 938, in parse_spec_inputs
    raise Exception(f"impossible value in rule: cde={key} value={value}")
Exception: impossible value in rule: cde=TNMCTLC value=cT*

**Comment by id2359** [comment]
Email from Angela: Stage IV rule for LC was a mistake, remove.
