### ISSUE TITLE
celeryworker picks up dash config

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2251]
celeryworker_1  | [ERROR:2022-10-19 09:41:52,503:signal.py:280:send] Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7f5fe371ea90>> raised: RuntimeError("Model class django_plotly_dash.models.StatelessApp doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.")
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 276, in send
celeryworker_1  |     response = receiver(signal=self, sender=sender, **named)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/fixups/django.py", line 82, in on_import_modules
celeryworker_1  |     self.worker_fixup.validate_models()
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/fixups/django.py", line 121, in validate_models
celeryworker_1  |     run_checks()
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
celeryworker_1  |     new_errors = check(app_configs=app_configs, databases=databases)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
celeryworker_1  |     return check_resolver(resolver)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
celeryworker_1  |     return check_method()
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
celeryworker_1  |     for pattern in self.url_patterns:
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
celeryworker_1  |     res = instance.__dict__[self.name] = self.func(instance)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
celeryworker_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
celeryworker_1  |     res = instance.__dict__[self.name] = self.func(instance)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
celeryworker_1  |     return import_module(self.urlconf_name)
celeryworker_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
celeryworker_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celeryworker_1  |   File "/app/rdrf/rdrf/urls.py", line 457, in <module>
celeryworker_1  |     re_path("dash/", include("django_plotly_dash.urls")),
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
celeryworker_1  |     urlconf_module = import_module(urlconf_module)
celeryworker_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
celeryworker_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django_plotly_dash/urls.py", line 30, in <module>
celeryworker_1  |     from .views import routes, layout, dependencies, update, main_view, component_suites, component_component_suites, asset_redirection, component_suites_build
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 42, in <module>
celeryworker_1  |     from .models import DashApp, check_stateless_loaded
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django_plotly_dash/models.py", line 43, in <module>
celeryworker_1  |     class StatelessApp(models.Model):
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/db/models/base.py", line 113, in __new__
celeryworker_1  |     raise RuntimeError(
celeryworker_1  | RuntimeError: Model class django_plotly_dash.models.StatelessApp doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
celeryworker_1  | [ERROR:2022-10-19 09:41:52,503:signal.py:280:send] Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7f5fe371ea90>> raised: RuntimeError("Model class django_plotly_dash.models.StatelessApp doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.")
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 276, in send
celeryworker_1  |     response = receiver(signal=self, sender=sender, **named)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/fixups/django.py", line 82, in on_import_modules
celeryworker_1  |     self.worker_fixup.validate_models()
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/fixups/django.py", line 121, in validate_models
celeryworker_1  |     run_checks()
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
celeryworker_1  |     new_errors = check(app_configs=app_configs, databases=databases)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
celeryworker_1  |     return check_resolver(resolver)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
celeryworker_1  |     return check_method()
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
celeryworker_1  |     for pattern in self.url_patterns:
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
celeryworker_1  |     res = instance.__dict__[self.name] = self.func(instance)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
celeryworker_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
celeryworker_1  |     res = instance.__dict__[self.name] = self.func(instance)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
celeryworker_1  |     return import_module(self.urlconf_name)
celeryworker_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
celeryworker_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celeryworker_1  |   File "/app/rdrf/rdrf/urls.py", line 457, in <module>
celeryworker_1  |     re_path("dash/", include("django_plotly_dash.urls")),
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
celeryworker_1  |     urlconf_module = import_module(urlconf_module)
celeryworker_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
celeryworker_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django_plotly_dash/urls.py", line 30, in <module>
celeryworker_1  |     from .views import routes, layout, dependencies, update, main_view, component_suites, component_component_suites, asset_redirection, component_suites_build
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 42, in <module>
celeryworker_1  |     from .models import DashApp, check_stateless_loaded
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django_plotly_dash/models.py", line 43, in <module>
celeryworker_1  |     class StatelessApp(models.Model):
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/db/models/base.py", line 113, in __new__
celeryworker_1  |     raise RuntimeError(
celeryworker_1  | RuntimeError: Model class django_plotly_dash.models.StatelessApp doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/env/bin/celery", line 8, in <module>
celeryworker_1  |     sys.exit(main())
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/__main__.py", line 15, in main
celeryworker_1  |     sys.exit(_main())
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/bin/celery.py", line 213, in main
celeryworker_1  |     return celery(auto_envvar_prefix="CELERY")
celeryworker_1  |   File "/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
celeryworker_1  |     return self.main(*args, **kwargs)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/click/core.py", line 782, in main
celeryworker_1  |     rv = self.invoke(ctx)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
celeryworker_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
celeryworker_1  |   File "/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
celeryworker_1  |     return ctx.invoke(self.callback, **ctx.params)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
celeryworker_1  |     return callback(*args, **kwargs)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
celeryworker_1  |     return f(get_current_context(), *args, **kwargs)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/bin/base.py", line 132, in caller
celeryworker_1  |     return f(ctx, *args, **kwargs)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/bin/worker.py", line 338, in worker
celeryworker_1  |     worker = app.Worker(
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/worker/worker.py", line 94, in __init__
celeryworker_1  |     self.app.loader.init_worker()
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/loaders/base.py", line 111, in init_worker
celeryworker_1  |     self.import_default_modules()
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/loaders/base.py", line 105, in import_default_modules
celeryworker_1  |     raise response
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 276, in send
celeryworker_1  |     response = receiver(signal=self, sender=sender, **named)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/fixups/django.py", line 82, in on_import_modules
celeryworker_1  |     self.worker_fixup.validate_models()
celeryworker_1  |   File "/env/lib/python3.8/site-packages/celery/fixups/django.py", line 121, in validate_models
celeryworker_1  |     run_checks()
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
celeryworker_1  |     new_errors = check(app_configs=app_configs, databases=databases)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
celeryworker_1  |     return check_resolver(resolver)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
celeryworker_1  |     return check_method()
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
celeryworker_1  |     for pattern in self.url_patterns:
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
celeryworker_1  |     res = instance.__dict__[self.name] = self.func(instance)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
celeryworker_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
celeryworker_1  |     res = instance.__dict__[self.name] = self.func(instance)
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
celeryworker_1  |     return import_module(self.urlconf_name)
celeryworker_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
celeryworker_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celeryworker_1  |   File "/app/rdrf/rdrf/urls.py", line 457, in <module>
celeryworker_1  |     re_path("dash/", include("django_plotly_dash.urls")),
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
celeryworker_1  |     urlconf_module = import_module(urlconf_module)
celeryworker_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
celeryworker_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django_plotly_dash/urls.py", line 30, in <module>
celeryworker_1  |     from .views import routes, layout, dependencies, update, main_view, component_suites, component_component_suites, asset_redirection, component_suites_build
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 42, in <module>
celeryworker_1  |     from .models import DashApp, check_stateless_loaded
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django_plotly_dash/models.py", line 43, in <module>
celeryworker_1  |     class StatelessApp(models.Model):
celeryworker_1  |   File "/env/lib/python3.8/site-packages/django/db/models/base.py", line 113, in __new__
celeryworker_1  |     raise RuntimeError(
celeryworker_1  | RuntimeError: Model class django_plotly_dash.models.StatelessApp doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by id2359** [comment]
seeing this in Travis also:

[log.txt](https://github.com/muccg/rdrf/files/9865164/log.txt)

**Comment by id2359** [comment]
fixed in 2250
