### ISSUE TITLE
celery error in HSS prod

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2253]
```
[ERROR:2022-10-25 07:10:23,699:trace.py:265:_log_error] Task rdrf.services.tasks.handle_hl7_message[aa8260ec-3f0e-432a-adcb-372fcd010d22] raised unexpected: EncodeError(TypeError('Object of type AssertionError is not JSON serializable'))
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 49, in _reraise_errors
    yield
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 65, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 55, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AssertionError is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/celery/app/trace.py", line 517, in trace_task
    mark_as_done(
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 161, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 477, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 904, in _store_result
    self._set_with_state(self.get_key_for_task(task_id), self.encode(meta), state)
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 367, in encode
    _, _, payload = self._encode(data)
  File "/env/lib/python3.8/site-packages/celery/backends/base.py", line 371, in _encode
    return dumps(data, serializer=self.serializer)
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 53, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/env/lib/python3.8/site-packages/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 49, in _reraise_errors
    yield
  File "/env/lib/python3.8/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 65, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/env/lib/python3.8/site-packages/kombu/utils/json.py", line 55, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type AssertionError is not JSON serializable
```

**Comment by id2359** [comment]
This was fixed in 6.6.49:   python-hl7 had been updated from 0.4.2 to 0.4.5 earlier. This actually broke the subscription. When the message model was being saved, assertion errors were being thrown from within python-hl7 ( not sure why ).

The error wan't being converted to a string  when we created wrote the result back to the redis backend which caused this error. In addition the assertions didn't have any message attached So logging the error in the cic logs produced a blank string.


In 6.6.49 this is resolved by rolling back python-hl7 to 0.4.2 ( subscriptions work) and fixing the logging.
