### ISSUE TITLE
dash error debug key error?

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2262]
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
    return self.application(environ, start_response)
  File "/env/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/env/lib/python3.8/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/rdrf/dashboards/views.py", line 91, in get
    return render(request, "rdrf_cdes/patients_dashboard.html", context)
  File "/env/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/env/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/env/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/env/lib/python3.8/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 91, in plotly_app
    da, app = _locate_daapp(name, slug, da, cache_id=cache_id)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 58, in _locate_daapp
    da, app = DashApp.locate_item(name, stateless=True, cache_id=cache_id)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/models.py", line 231, in locate_item
    app = dash_app.as_dash_instance(cache_id=cache_id)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 226, in as_dash_instance
    return self.do_form_dash_instance(cache_id=cache_id)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 262, in do_form_dash_instance
    return self.form_dash_instance(replacements, ndid, base_pathname)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 270, in form_dash_instance
    rd = WrappedDash(base_pathname=base_pathname,
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 428, in __init__
    super().__init__(__name__, **kwargs)
  File "/env/lib/python3.8/site-packages/dash/dash.py", line 494, in __init__
    self.init_app()
  File "/env/lib/python3.8/site-packages/dash/dash.py", line 558, in init_app
    self.server.before_request(self._setup_server)
  File "/env/lib/python3.8/site-packages/flask/scaffold.py", line 39, in wrapper_func
    if self._is_setup_finished():
  File "/env/lib/python3.8/site-packages/flask/app.py", line 517, in _is_setup_finished
    return self.debug and self._got_first_request
  File "/env/lib/python3.8/site-packages/flask/app.py", line 792, in debug
    return self.config["DEBUG"]
KeyError: 'DEBUG'

**Comment by id2359** [comment]
Possible this is a regression in DPD, not sure . I asked on there github and raised  issue 425

Somebody responded with "Seems to be a new incompatability to dash 2.7.0 which wasnt present in 2.6.2"

**Comment by id2359** [comment]
Will pin Dash at 2.6.2 and use DPD 2.0.0 and see.
