### ISSUE TITLE
another build fail FAIL: Admin user blocks useraudit to localhost (features.base_iprestrict: IPRestrict is enabled and working)

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2295]
26146 FAIL: Admin user blocks useraudit to localhost (features.base_iprestrict: IPRestrict is enabled and working)^M
26147 ----------------------------------------------------------------------^M
26148 Traceback (most recent call last):^M
26149   File "/env/lib/python3.8/site-packages/aloe/registry.py", line 151, in wrapped^M
26150     return function(*args, **kwargs)^M
26151   File "/app/rdrf/rdrf/testing/behaviour/features/base_iprestrict.feature", line 24, in Admin user blocks useraudit to localhost^M
26152     Then I should see "Looks like you don't have access to this page"^M
26153   File "/env/lib/python3.8/site-packages/aloe/registry.py", line 151, in wrapped^M
26154     return function(*args, **kwargs)^M
26155   File "/app/rdrf/rdrf/testing/behaviour/features/steps.py", line 170, in should_see^M
26156     assert_true(contains_content(world.browser, text))^M
26157 AssertionError: False is not true^M

**Comment by id2359** [comment]
This implies iprestrict is either disabled or not working ( or both/)

I've disabled the test for now - will fix later as CIC not using IPRestrict.

**Comment by id2359** [comment]
ERROR: b'/env/bin/django-admin.py:17: RemovedInDjango40Warning: django-admin.py is deprecated in favor of django-admin why is this an error? ( suddenly)?
