### ISSUE TITLE
prod build fails

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2296]
======================================================================
ERROR: Admin user drop-down has Admin Page item (features.base_admin_page: Admin Page and Settings)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/aloe/registry.py", line 151, in wrapped
    return function(*args, **kwargs)
  File "/app/rdrf/rdrf/testing/behaviour/features/base_admin_page.feature", line 11, in Admin user drop-down has Admin Page item
    Given I am logged in as admin
  File "/env/lib/python3.8/site-packages/aloe/registry.py", line 151, in wrapped
    return function(*args, **kwargs)
  File "/app/rdrf/rdrf/testing/behaviour/features/steps.py", line 517, in login_as_role
    go_to_registry(step, world.registry)
  File "/app/rdrf/rdrf/testing/behaviour/features/steps.py", line 566, in go_to_registry
    utils.click(world.browser.find_element_by_link_text('Registries on this site'))
  File "/env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 754, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/env/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Registries on this site"}
  (Session info: chrome=61.0.3163.91)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.15.0-1098-gcp x86_64)
-------------------- >> begin captured logging << --------------------
features.utils: ERROR: b'/env/bin/django-admin.py:17: RemovedInDjango40Warning: django-admin.py is deprecated in favor of django-admin.\n  warnings.warn(\n/env/lib/python3.8/site-packages/dash_bootstrap_components/_table.py:5: UserWarning: \nThe dash_html_components package is deprecated. Please replace\n`import dash_html_components as html` with `from dash import html`\n  import dash_html_components as html\n'
features.utils: ERROR: b'/env/bin/django-admin.py:17: RemovedInDjango40Warning: django-admin.py is deprecated in favor of django-admin.\n  warnings.warn(\n/env/lib/python3.8/site-packages/dash_bootstrap_components/_table.py:5: UserWarning: \nThe dash_html_components package is deprecated. Please replace\n`import dash_html_components as html` with `from dash import html`\n  import dash_html_components as html\n'
features.utils: INFO: b'Operations to perform:\n  Apply all migrations: admin, auth, contenttypes, dashboards, django_plotly_dash, explorer, genetic, groups, intframework, otp_static, otp_totp, patients, rdrf, registration, reversion, sessions, sites, two_factor, useraudit\nRunning migrations:\n  No migrations to apply.\n'
features.utils: ERROR: b'/env/bin/django-admin.py:17: RemovedInDjango40Warning: django-admin.py is deprecated in favor of django-admin.\n  warnings.warn(\n/env/lib/python3.8/site-packages/dash_bootstrap_components/_table.py:5: UserWarning: \nThe dash_html_components package is deprecated. Please replace\n`import dash_html_components as html` with `from dash import html`\n  import dash_html_components as html\n'
features.utils: INFO: b'Operations to perform:\n  Apply all migrations: admin, auth, contenttypes, dashboards, django_plotly_dash, explorer, genetic, groups, intframework, otp_static, otp_totp, patients, rdrf, registration, reversion, sessions, sites, two_factor, useraudit\nRunning migrations:\n  No migrations to apply.\n'
features.utils: ERROR: b'/env/bin/django-admin.py:17: RemovedInDjango40Warning: django-admin.py is deprecated in favor of django-admin.\n  warnings.warn(\n/env/lib/python3.8/site-packages/dash_bootstrap_components/_table.py:5: UserWarning: \nThe dash_html_components package is deprecated. Please replace\n`import dash_html_components as html` with `from dash import html`\n  import dash_html_components as html\n'
features.utils: INFO: b'\n'
features.utils: ERROR: b"/env/lib/python3.8/site-packages/sqlalchemy/sql/functions.py:65: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overridden.\n  util.warn(\n"
features.utils: INFO: b'\n'
features.utils: ERROR: b"/env/lib/python3.8/site-packages/sqlalchemy/sql/functions.py:65: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overridden.\n  util.warn(\n"
features.utils: INFO: b'Snapshotting database webapp\n'
features.utils: ERROR: b"/env/lib/python3.8/site-packages/sqlalchemy/sql/functions.py:65: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overridden.\n  util.warn(\n/env/lib/python3.8/site-packages/sqlalchemy/sql/functions.py:65: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overridden.\n  util.warn(\n"
features.utils: INFO: b'Snapshotting database webapp\n'
features.utils: ERROR: b"/env/lib/python3.8/site-packages/sqlalchemy/sql/functions.py:65: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overridden.\n  util.warn(\n/env/lib/python3.8/site-packages/sqlalchemy/sql/functions.py:65: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overridden.\n  util.warn(\n"
selenium.webdriver.remote.remote_connection: DEBUG: POST http://172.18.0.2:4444/wd/hub/session {"desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "javascriptEnabled": true}, "requiredCapabilities": {}}
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
selenium.webdriver.remote.remote_connection: DEBUG: POST http://172.18.0.2:4444/wd/hub/session/c5a7cfd0a206276f7dcecb25920da041/timeouts/implicit_wait {"ms": 10000.0, "sessionId": "c5a7cfd0a206276f7dcecb25920da041"}
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
selenium.webdriver.remote.remote_connection: DEBUG: DELETE http://172.18.0.2:4444/wd/hub/session/c5a7cfd0a206276f7dcecb25920da041/cookie {"sessionId": "c5a7cfd0a206276f7dcecb25920da041"}
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
features.utils: INFO: b'Loading RDRF data...\n    Loading base...\n    Loading reference_data...\n    Loading groups...\n    Loading users...\n    Loading sample_laboratories...\n    Loading genes_smaller_sample...\n    Loading sample_registry...\n    Loading iprestrict_permissive...\n    Loading DEV...\nRDRF data is ready.\n'
features.utils: ERROR: b'/env/bin/django-admin.py:17: RemovedInDjango40Warning: django-admin.py is deprecated in favor of django-admin.\n  warnings.warn(\n/env/lib/python3.8/site-packages/dash_bootstrap_components/_table.py:5: UserWarning: \nThe dash_html_components package is deprecated. Please replace\n`import dash_html_components as html` with `from dash import html`\n  import dash_html_components as html\n'
features.utils: ERROR: b'/env/bin/django-admin.py:17: RemovedInDjango40Warning: django-admin.py is deprecated in favor of django-admin.\n  warnings.warn(\n/env/lib/python3.8/site-packages/dash_bootstrap_components/_table.py:5: UserWarning: \nThe dash_html_components package is deprecated. Please replace\n`import dash_html_components as html` with `from dash import html`\n  import dash_html_components as html\nTraceback (most recent call last):\n  File "/env/bin/django-admin.py", line 21, in <module>\n    management.execute_from_command_line()\n  File "/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line\n    utility.execute()\n  File "/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File "/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File "/env/lib/python3.8/site-packages/django/core/management/base.py", line 393, in execute\n    self.check()\n  File "/env/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check\n    all_issues = checks.run_checks(\n  File "/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks\n    new_errors = check(app_configs=app_configs, databases=databases)\n  File "/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config\n    return check_resolver(resolver)\n  File "/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver\n    return check_method()\n  File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check\n    for pattern in self.url_patterns:\n  File "/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns\n    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)\n  File "/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File "/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module\n    return import_module(self.urlconf_name)\n  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import\n  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\n  File "<frozen importlib._bootstrap_external>", line 783, in exec_module\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n  File "/app/rdrf/rdrf/urls.py", line 462, in <module>\n    re_path(r"^dashboards/", include(("dashboards.urls", "dashboards"))),\n  File "/env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include\n    urlconf_module = import_module(urlconf_module)\n  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import\n  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\n  File "<frozen importlib._bootstrap_external>", line 783, in exec_module\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n  File "/app/rdrf/dashboards/urls.py", line 6, in <module>\n    from .dash_apps import single_app, all_app\n  File "/app/rdrf/dashboards/dash_apps.py", line 45, in <module>\n    active_tab=f"tab_{single_configs[0].id}",\n  File "/env/lib/python3.8/site-packages/django/db/models/query.py", line 300, in __getitem__\n    return self._result_cache[k]\nIndexError: list index out of range\n'
features.utils: ERROR: Return code 1
selenium.webdriver.remote.remote_connection: DEBUG: POST http://172.18.0.2:4444/wd/hub/session/c5a7cfd0a206276f7dcecb25920da041/url {"url": "https://nginxtest:443/app/", "sessionId": "c5a7cfd0a206276f7dcecb25920da041"}
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
selenium.webdriver.remote.remote_connection: DEBUG: POST http://172.18.0.2:4444/wd/hub/session/c5a7cfd0a206276f7dcecb25920da041/element {"using": "link text", "value": "Registries on this site", "sessionId": "c5a7cfd0a206276f7dcecb25920da041"}
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
selenium.webdriver.remote.remote_connection: DEBUG: GET http://172.18.0.2:4444/wd/hub/session/c5a7cfd0a206276f7dcecb25920da041/screenshot {"sessionId": "c5a7cfd0a206276f7dcecb25920da041"}
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
selenium.webdriver.remote.remote_connection: DEBUG: GET http://172.18.0.2:4444/wd/hub/session/c5a7cfd0a206276f7dcecb25920da041/screenshot {"sessionId": "c5a7cfd0a206276f7dcecb25920da041"}
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
features.utils: INFO: b'Restoring database webapp\nRestore complete.\n'
features.utils: ERROR: b"/env/lib/python3.8/site-packages/sqlalchemy/sql/functions.py:65: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overridden.\n  util.warn(\n/env/lib/python3.8/site-packages/sqlalchemy/sql/functions.py:65: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overridden.\n  util.warn(\n"
features.utils: INFO: b'Restoring database webapp\nRestore complete.\n'
features.utils: ERROR: b"/env/lib/python3.8/site-packages/sqlalchemy/sql/functions.py:65: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overridden.\n  util.warn(\n/env/lib/python3.8/site-packages/sqlalchemy/sql/functions.py:65: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overridden.\n  util.warn(\n"
--------------------- >> end captured logging << ---------------------

**Comment by id2359** [comment]
ERROR: b'/env/bin/django-admin.py:17: RemovedInDjango40Warning: django-admin.py is deprecated in favor of django-admin why is this an error? ( suddenly)?
