### ISSUE TITLE
Vis Feedback Round 2 - Is it possible to add the average values to the Functional tab for the individual patients and the Pain tab?

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2312]
Is it possible to add the average values to 1) the Functional tab for the individual patients and 2) the Pain tab?

**Comment by id2359** [comment]
tested locally with functional:
runserver_1     | [INFO:2023-01-24 12:42:57,636:sgc.py:104:get_graphic] calculating averages for the scores..
runserver_1     | [INFO:2023-01-24 12:42:57,637:sgc.py:111:get_graphic] time taken to calculate average scores for all patients = 0.001359 seconds
runserver_1     | [DEBUG:2023-01-24 12:42:57,640:sgc.py:182:get_line_chart] get line chart for Scores over time for <i class="text-muted"><span class="fa fa-user" aria-hidden="true"></span> <a href='/ICHOMCRC/patient/8034/edit'>BLACK Fred1025</a></i> <i>( Higher score is better )</i>
runserver_1     | 172.27.0.1 - - [24/Jan/2023 12:42:57] "POST /dash/app/SinglePatientDashboardApp/_dash-update-component HTTP/1.1" 500 -
runserver_1     | Traceback (most recent call last):
runserver_1     |   File "/env/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
runserver_1     |     return self.application(environ, start_response)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
runserver_1     |     response = self.get_response(request)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
runserver_1     |     response = self._middleware_chain(request)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
runserver_1     |     response = response_for_exception(request, exc)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
runserver_1     |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
runserver_1     |     return debug.technical_500_response(request, *exc_info)
runserver_1     |   File "/env/lib/python3.8/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
runserver_1     |     raise exc_value.with_traceback(tb)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
runserver_1     |     response = get_response(request)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
runserver_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
runserver_1     |     return view_func(*args, **kwargs)
runserver_1     |   File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
runserver_1     |     return _update(request, ident, stateless, **kwargs)
runserver_1     |   File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
runserver_1     |     resp = app.dispatch_with_args(request_body, arg_map)
runserver_1     |   File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 703, in dispatch_with_args
runserver_1     |     res = callback(*args, **argMap)
runserver_1     |   File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
runserver_1     |     output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
runserver_1     |   File "/app/rdrf/dashboards/dash_apps.py", line 77, in render_tab_content
runserver_1     |     graphics_map = get_single_patient_graphics_map(
runserver_1     |   File "/app/rdrf/dashboards/utils.py", line 203, in get_single_patient_graphics_map
runserver_1     |     graphics_map = {
runserver_1     |   File "/app/rdrf/dashboards/utils.py", line 204, in <dictcomp>
runserver_1     |     f"tab_{vc.id}": create_graphic(vc, data, patient, None) for vc in vis_configs
runserver_1     |   File "/app/rdrf/dashboards/utils.py", line 158, in create_graphic
runserver_1     |     return ScaleGroupComparison(
runserver_1     |   File "/app/rdrf/dashboards/components/common.py", line 51, in graphic
runserver_1     |     return self.get_graphic()
runserver_1     |   File "/app/rdrf/dashboards/components/sgc.py", line 155, in get_graphic
runserver_1     |     line_chart = self.get_line_chart(data, chart_title, scores_map)
runserver_1     |   File "/app/rdrf/dashboards/components/sgc.py", line 185, in get_line_chart
runserver_1     |     fig = px.line(
runserver_1     |   File "/env/lib/python3.8/site-packages/plotly/express/_chart_types.py", line 264, in line
runserver_1     |     return make_figure(args=locals(), constructor=go.Scatter)
runserver_1     |   File "/env/lib/python3.8/site-packages/plotly/express/_core.py", line 1990, in make_figure
runserver_1     |     args = build_dataframe(args, constructor)
runserver_1     |   File "/env/lib/python3.8/site-packages/plotly/express/_core.py", line 1405, in build_dataframe
runserver_1     |     df_output, wide_id_vars = process_args_into_dataframe(
runserver_1     |   File "/env/lib/python3.8/site-packages/plotly/express/_core.py", line 1245, in process_args_into_dataframe
runserver_1     |     raise ValueError(
runserver_1     | ValueError: All arguments should have the same length. The length of argument `y` is 4, whereas the length of  previously-processed arguments ['SEQ'] is 16

**Comment by id2359** [comment]
I added compare_all to bother groups and this disappeared.
