### ISSUE TITLE
Vis Feedback Round 2 - Missing baseline - no visualisations shown

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2313]
staging Lois lane (has a follow up but no baseline data) – no visualisations showing.  We will need this to be visible as some people may just miss out on baseline but then have several follow ups OR because of treatment location circumstances they may start involvement in CIC at a follow up point.

**Comment by id2359** [comment]
If the baseline form ( containing collection date) is not saved , RDRF will still show the sgc graphic ( with baseline showing for the average scores)
Something else is going wrong here probably.

**Comment by id2359** [comment]
The log shows:
```
FO:2023-01-30 15:40:49,355:sgc.py:93:get_graphic] calculating scores for all patients..
[INFO:2023-01-30 15:40:49,407:sgc.py:383:calculate_scores] score score_0 time = 0.004857 seconds
[INFO:2023-01-30 15:40:49,464:sgc.py:383:calculate_scores] score score_1 time = 0.005377 seconds
[INFO:2023-01-30 15:40:49,465:sgc.py:99:get_graphic] time taken to calculate all scores for all patients = 0.10982 seconds
[INFO:2023-01-30 15:40:49,465:sgc.py:104:get_graphic] calculating averages for the scores..
[INFO:2023-01-30 15:40:49,477:sgc.py:111:get_graphic] time taken to calculate average scores for all patients = 0.011511 seconds
[ERROR:2023-01-30 15:40:50,453:log.py:224:log_response] Internal Server Error: /cicclinical/dash/app/SinglePatientDashboardApp/_dash-update-component
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 700, in dispatch_with_args
    res = callback(*args, **argMap)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/env/lib/python3.8/site-packages/dashboards/dash_apps.py", line 77, in render_tab_content
    graphics_map = get_single_patient_graphics_map(
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 200, in get_single_patient_graphics_map
    graphics_map = {
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 201, in <dictcomp>
    f"tab_{vc.id}": create_graphic(vc, data, patient, None) for vc in vis_configs
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 157, in create_graphic
    return ScaleGroupComparison(
  File "/env/lib/python3.8/site-packages/dashboards/components/common.py", line 51, in graphic
    return self.get_graphic()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 155, in get_graphic
    line_chart = self.get_line_chart(data, chart_title, scores_map)
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 185, in get_line_chart
    fig = px.line(
  File "/env/lib/python3.8/site-packages/plotly/express/_chart_types.py", line 264, in line
    return make_figure(args=locals(), constructor=go.Scatter)
  File "/env/lib/python3.8/site-packages/plotly/express/_core.py", line 1991, in make_figure
    args = build_dataframe(args, constructor)
  File "/env/lib/python3.8/site-packages/plotly/express/_core.py", line 1453, in build_dataframe
    raise ValueError(
ValueError: Plotly Express cannot process wide-form data with columns of different type.
[INFO:2023-01-30 15:41:17,663:dash_apps.py:121:<module>] all_app defined
[INFO:2023-01-30 15:42:03,676:dash_apps.py:68:render_tab_content] dash app single_app callback
[INFO:2023-01-30 15:42:03,677:dash_apps.py:71:render_tab_content] single app callback: active_tab = tab_20
[INFO:2023-01-30 15:42:03,727:data.py:76:__init__] time taken to load/generate df = 0.039046 seconds
[INFO:2023-01-30 15:42:03,728:sgc.py:16:log] sgc: creating Scale Group Comparison
[INFO:2023-01-30 15:42:03,774:sgc.py:16:log] sgc: scale is functional
[INFO:2023-01-30 15:42:03,774:sgc.py:67:get_graphic] calculating score for Physical and Role Functioning
[INFO:2023-01-30 15:42:03,823:sgc.py:383:calculate_scores] score score_0 time = 0.002614 seconds
[INFO:2023-01-30 15:42:03,874:sgc.py:16:log] sgc: scale is functional
[INFO:2023-01-30 15:42:03,875:sgc.py:67:get_graphic] calculating score for Emotional, Cognitive and Social Functioning
[INFO:2023-01-30 15:42:03,929:sgc.py:383:calculate_scores] score score_1 time = 0.00264 seconds
[INFO:2023-01-30 15:42:03,929:sgc.py:87:get_graphic] all patients data not loaded - loading ..
[INFO:2023-01-30 15:42:03,937:data.py:70:__init__] loading dataframe from base config json
[INFO:2023-01-30 15:42:03,960:data.py:76:__init__] time taken to load/generate df = 0.023106 seconds
[INFO:2023-01-30 15:42:03,960:sgc.py:91:get_graphic] time taken = 0.03041 seconds
[INFO:2023-01-30 15:42:03,960:sgc.py:93:get_graphic] calculating scores for all patients..
[INFO:2023-01-30 15:42:04,012:sgc.py:383:calculate_scores] score score_0 time = 0.004683 seconds
[INFO:2023-01-30 15:42:04,071:sgc.py:383:calculate_scores] score score_1 time = 0.005243 seconds
[INFO:2023-01-30 15:42:04,072:sgc.py:99:get_graphic] time taken to calculate all scores for all patients = 0.110975 seconds
[INFO:2023-01-30 15:42:04,072:sgc.py:104:get_graphic] calculating averages for the scores..
[INFO:2023-01-30 15:42:04,075:sgc.py:111:get_graphic] time taken to calculate average scores for all patients = 0.003394 seconds
[ERROR:2023-01-30 15:42:04,979:log.py:224:log_response] Internal Server Error: /cicclinical/dash/app/SinglePatientDashboardApp/_dash-update-component
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 700, in dispatch_with_args
    res = callback(*args, **argMap)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/env/lib/python3.8/site-packages/dashboards/dash_apps.py", line 77, in render_tab_content
    graphics_map = get_single_patient_graphics_map(
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 200, in get_single_patient_graphics_map
    graphics_map = {
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 201, in <dictcomp>
    f"tab_{vc.id}": create_graphic(vc, data, patient, None) for vc in vis_configs
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 157, in create_graphic
    return ScaleGroupComparison(
  File "/env/lib/python3.8/site-packages/dashboards/components/common.py", line 51, in graphic
    return self.get_graphic()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 155, in get_graphic
    line_chart = self.get_line_chart(data, chart_title, scores_map)
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 185, in get_line_chart
    fig = px.line(
  File "/env/lib/python3.8/site-packages/plotly/express/_chart_types.py", line 264, in line
    return make_figure(args=locals(), constructor=go.Scatter)
  File "/env/lib/python3.8/site-packages/plotly/express/_core.py", line 1991, in make_figure
    args = build_dataframe(args, constructor)
  File "/env/lib/python3.8/site-packages/plotly/express/_core.py", line 1453, in build_dataframe
    raise ValueError(
ValueError: Plotly Express cannot process wide-form data with columns of different type.
[INFO:2023-01-30 15:42:07,650:dash_apps.py:68:render_tab_content] dash app single_app callback
[INFO:2023-01-30 15:42:07,651:dash_apps.py:71:render_tab_content] single app callback: active_tab = tab_25
[INFO:2023-01-30 15:42:07,701:data.py:76:__init__] time taken to load/generate df = 0.037979 seconds
[INFO:2023-01-30 15:42:07,701:sgc.py:16:log] sgc: creating Scale Group Comparison
[INFO:2023-01-30 15:42:07,747:sgc.py:16:log] sgc: scale is functional
[INFO:2023-01-30 15:42:07,747:sgc.py:67:get_graphic] calculating score for Physical and Role Functioning
[INFO:2023-01-30 15:42:07,796:sgc.py:383:calculate_scores] score score_0 time = 0.002324 seconds
[INFO:2023-01-30 15:42:07,847:sgc.py:16:log] sgc: scale is functional
[INFO:2023-01-30 15:42:07,848:sgc.py:67:get_graphic] calculating score for Emotional, Cognitive and Social Functioning
[INFO:2023-01-30 15:42:07,902:sgc.py:383:calculate_scores] score score_1 time = 0.00234 seconds
[INFO:2023-01-30 15:42:07,902:sgc.py:87:get_graphic] all patients data not loaded - loading ..
[INFO:2023-01-30 15:42:07,909:data.py:70:__init__] loading dataframe from base config json
[INFO:2023-01-30 15:42:07,934:data.py:76:__init__] time taken to load/generate df = 0.024451 seconds
[INFO:2023-01-30 15:42:07,934:sgc.py:91:get_graphic] time taken = 0.031919 seconds
[INFO:2023-01-30 15:42:07,934:sgc.py:93:get_graphic] calculating scores for all patients..
[INFO:2023-01-30 15:42:07,986:sgc.py:383:calculate_scores] score score_0 time = 0.004732 seconds
[INFO:2023-01-30 15:42:08,050:sgc.py:383:calculate_scores] score score_1 time = 0.005471 seconds
[INFO:2023-01-30 15:42:08,050:sgc.py:99:get_graphic] time taken to calculate all scores for all patients = 0.115701 seconds
[INFO:2023-01-30 15:42:08,050:sgc.py:104:get_graphic] calculating averages for the scores..
[INFO:2023-01-30 15:42:08,054:sgc.py:111:get_graphic] time taken to calculate average scores for all patients = 0.003422 seconds
[ERROR:2023-01-30 15:42:08,971:log.py:224:log_response] Internal Server Error: /cicclinical/dash/app/SinglePatientDashboardApp/_dash-update-component
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 700, in dispatch_with_args
    res = callback(*args, **argMap)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/env/lib/python3.8/site-packages/dashboards/dash_apps.py", line 77, in render_tab_content
    graphics_map = get_single_patient_graphics_map(
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 200, in get_single_patient_graphics_map
    graphics_map = {
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 201, in <dictcomp>
    f"tab_{vc.id}": create_graphic(vc, data, patient, None) for vc in vis_configs
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 157, in create_graphic
    return ScaleGroupComparison(
  File "/env/lib/python3.8/site-packages/dashboards/components/common.py", line 51, in graphic
    return self.get_graphic()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 155, in get_graphic
    line_chart = self.get_line_chart(data, chart_title, scores_map)
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 185, in get_line_chart
    fig = px.line(
  File "/env/lib/python3.8/site-packages/plotly/express/_chart_types.py", line 264, in line
    return make_figure(args=locals(), constructor=go.Scatter)
  File "/env/lib/python3.8/site-packages/plotly/express/_core.py", line 1991, in make_figure
    args = build_dataframe(args, constructor)
  File "/env/lib/python3.8/site-packages/plotly/express/_core.py", line 1453, in build_dataframe
    raise ValueError(
ValueError: Plotly Express cannot process wide-form data with columns of different type.

```

**Comment by id2359** [comment]
bad data on staging, marking as invalid
