### ISSUE TITLE
Error in sgc when not enough datapoints

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2367]
The runtime error is:
```
[INFO:2023-02-08 11:08:19,836:data.py:71:__init__] loading dataframe from base config json
runserver_1     | [INFO:2023-02-08 11:08:19,953:data.py:79:__init__] time taken to load/generate df = 0.117408 seconds
runserver_1     | [DEBUG:2023-02-08 11:08:20,055:data.py:360:combine_data] combined data including counts =     PID  SEQ      TYPE  ...  score_0 avg_score_0 count_score_0
runserver_1     | 0  9010    0  baseline  ...     None   58.503401           490
runserver_1     | 
runserver_1     | [1 rows x 75 columns]
runserver_1     | 172.27.0.1 - - [08/Feb/2023 11:08:20] "POST /dash/app/SinglePatientDashboardApp/_dash-update-component HTTP/1.1" 500 -
runserver_1     | Traceback (most recent call last):
runserver_1     |   File "/env/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
runserver_1     |     return self.application(environ, start_response)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
runserver_1     |     response = self.get_response(request)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
runserver_1     |     response = self._middleware_chain(request)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
runserver_1     |     response = response_for_exception(request, exc)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
runserver_1     |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
runserver_1     |     return debug.technical_500_response(request, *exc_info)
runserver_1     |   File "/env/lib/python3.8/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
runserver_1     |     raise exc_value.with_traceback(tb)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
runserver_1     |     response = get_response(request)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
runserver_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
runserver_1     |   File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
runserver_1     |     return view_func(*args, **kwargs)
runserver_1     |   File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
runserver_1     |     return _update(request, ident, stateless, **kwargs)
runserver_1     |   File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
runserver_1     |     resp = app.dispatch_with_args(request_body, arg_map)
runserver_1     |   File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 703, in dispatch_with_args
runserver_1     |     res = callback(*args, **argMap)
runserver_1     |   File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
runserver_1     |     output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
runserver_1     |   File "/app/rdrf/dashboards/dash_apps.py", line 85, in render_tab_content
runserver_1     |     graphics_map = get_single_patient_graphics_map(
runserver_1     |   File "/app/rdrf/dashboards/utils.py", line 204, in get_single_patient_graphics_map
runserver_1     |     graphics_map = {
runserver_1     |   File "/app/rdrf/dashboards/utils.py", line 205, in <dictcomp>
runserver_1     |     f"tab_{vc.id}": create_graphic(vc, data, patient, None) for vc in vis_configs
runserver_1     |   File "/app/rdrf/dashboards/utils.py", line 161, in create_graphic
runserver_1     |     return ScaleGroupComparison(
runserver_1     |   File "/app/rdrf/dashboards/components/common.py", line 54, in graphic
runserver_1     |     return self.get_graphic()
runserver_1     |   File "/app/rdrf/dashboards/components/sgc.py", line 137, in get_graphic
runserver_1     |     line_chart = self.get_line_chart(data, chart_title, scores_map)
runserver_1     |   File "/app/rdrf/dashboards/components/sgc.py", line 199, in get_line_chart
runserver_1     |     fig = px.line(
runserver_1     |   File "/env/lib/python3.8/site-packages/plotly/express/_chart_types.py", line 264, in line
runserver_1     |     return make_figure(args=locals(), constructor=go.Scatter)
runserver_1     |   File "/env/lib/python3.8/site-packages/plotly/express/_core.py", line 1990, in make_figure
runserver_1     |     args = build_dataframe(args, constructor)
runserver_1     |   File "/env/lib/python3.8/site-packages/plotly/express/_core.py", line 1452, in build_dataframe
runserver_1     |     raise ValueError(
runserver_1     | ValueError: Plotly Express cannot process wide-form data with columns of different type.

```

**Comment by id2359** [comment]
Can't browse to the other tabs either

**Comment by id2359** [comment]
If a patient has some scores it seems to work without fillna(-1)???

The line datapoint is missed out 
with fillna(-1) the behaviour is to show the line heading towards -1 which is wrong
so reopening

**Comment by id2359** [comment]
I believe this is when there is no score data ( i.e. no traces)

If there is one trace with a datapoint in an sequence number, another trace can miss out that sequence number ( be NA)

If all traces are NA for that sequence number we get an error.

But if the entire form missed ( i.e. no baseline form saved ) this is ok

**Comment by id2359** [comment]
Did the following:

- Produce datatable from data containing Nones
- For the figure, fillna with -1 to avoid the Value Error
- Update the traces with numpy to delete the dummy -1 values
- Wrapped the get_graphic function in utils to return a message on any other Value error
