### ISSUE TITLE
Weuzkeug update broke runserver

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2393]
runserver_1     | Exception happened during processing of request from ('172.18.0.1', 53782)
runserver_1     | Traceback (most recent call last):
runserver_1     |   File "/usr/local/lib/python3.8/socketserver.py", line 650, in process_request_thread
runserver_1     |     self.finish_request(request, client_address)
runserver_1     |   File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
runserver_1     |     self.RequestHandlerClass(request, client_address, self)
runserver_1     |   File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
runserver_1     |     self.handle()
runserver_1     |   File "/env/lib/python3.8/site-packages/werkzeug/serving.py", line 361, in handle
runserver_1     |     super().handle()
runserver_1     |   File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
runserver_1     |     self.handle_one_request()
runserver_1     |   File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
runserver_1     |     method()
runserver_1     |   File "/env/lib/python3.8/site-packages/werkzeug/serving.py", line 241, in run_wsgi
runserver_1     |     self.environ = environ = self.make_environ()
runserver_1     |   File "/env/lib/python3.8/site-packages/django_extensions/management/commands/runserver_plus.py", line 322, in make_environ
runserver_1     |     del environ['werkzeug.server.shutdown']
runserver_1     | KeyError: 'werkzeug.server.shutdown'

**Comment by id2359** [comment]
https://stackoverflow.com/questions/72166259/werkzeug-server-is-shutting-down-in-django-application

**Comment by id2359** [comment]
Updated django extensions to 3.2.1 - this fixes the weukzeug issue
