### ISSUE TITLE
HSS UAT Testing - CRC  tab loading issue - 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2440]
LM:

One issue I’ve found with UAT is probably related to the issue previously found with the dashboards not moving well between tabs.  I found this morning that whilst I could get to the right page when I clicked on a tab it kept reverting to the content of the previous one I’d been in.  For example I was moving through the tabs and when I got to Traffic light tumour it would open but then revert back to the content of the Global Health tab. You can see in screenshot that the 3rd tab is highlighted as being open but what the user sees is the content of the 2nd tab (the one previously opened).  I tried a number of times but it just kept reverting to Global Health and then wouldn’t open traffic light tumour at all. At one point the traffic lights showed up but under the banner of Global health (see attached photo – had to do a photo as this oddity didn’t last long and then reverted to line graph of global health under that tab name). A bug I think.  Bottom line users are unable to scroll down the traffic lights and study the content properly.
 

I found the same thing when I looked at the Financial tab and then tried to go to the Traffic Lights-Generic tab.  That one settled on the correct content after several attempts but pretty frustrating.  Seems to favour the line graphs over the traffic lights each time as it doesn’t seem to occur when opening line graph tabs.

**Comment by id2359** [comment]
I do see some JS errors loading 

patient [AACICPATIENT1 PATIENT 1 UPDATE]

(https://ciccancersitesystemuat.hdwa.health.wa.gov.au/crc/externaldemographics/ICHOMCRC/34)

I go to the dashboard:

click on Traffic Lights generic - ok
click on global health status/qol - ok



The xx tab 
https://ciccancersitesystemuat.hdwa.health.wa.gov.au/crc/externaldemographics/ICHOMCRC/34





react-dom.production.min.js:125 Error: The target 'image_EORTCQLQC29_Q48__1' could not be identified in the dom, tip: check spelling
    at B (dash_bootstrap_components.min.js:31:67362)
    at W (dash_bootstrap_components.min.js:31:67570)
    at n.updateTarget (dash_bootstrap_components.min.js:31:224892)
    at n.componentDidMount (dash_bootstrap_components.min.js:31:221204)
    at oj (react-dom.production.min.js:127:59)
    at Aj (react-dom.production.min.js:160:448)
    at unstable_runWithPriority (react.production.min.js:25:260)
    at Da (react-dom.production.min.js:60:280)
    at ab (react-dom.production.min.js:154:190)
    at Te (react-dom.production.min.js:146:355)
Me @ react-dom.production.min.js:125
react-dom.production.min.js:125 Error: The target 'image_EORTCQLQC29_Q48__1' could not be identified in the dom, tip: check spelling
    at B (dash_bootstrap_components.min.js:31:67362)
    at W (dash_bootstrap_components.min.js:31:67570)
    at n.updateTarget (dash_bootstrap_components.min.js:31:224892)
    at n.componentDidMount (dash_bootstrap_components.min.js:31:221204)
    at oj (react-dom.production.min.js:127:59)
    at Aj (react-dom.production.min.js:160:448)
    at unstable_runWithPriority (react.production.min.js:25:260)
    at Da (react-dom.production.min.js:60:280)
    at ab (react-dom.production.min.js:154:190)
    at Te (react-dom.production.min.js:146:355)
Me @ react-dom.production.min.js:125
Jh.c.payload @ react-dom.production.min.js:138
Qb @ react-dom.production.min.js:66
rh @ react-dom.production.min.js:101
zj @ react-dom.production.min.js:228
Th @ react-dom.production.min.js:152
tj @ react-dom.production.min.js:152
Te @ react-dom.production.min.js:146
(anonymous) @ react-dom.production.min.js:61
unstable_runWithPriority @ react.production.min.js:25
Da @ react-dom.production.min.js:60
Pg @ react-dom.production.min.js:61
ha @ react-dom.production.min.js:60
Qh @ react-dom.production.min.js:147
notify @ dash_renderer.min.js:2
notifyNestedSubs @ dash_renderer.min.js:2
o @ dash_renderer.min.js:2
p @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
e @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
e @ dash_renderer.min.js:2
observer @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
e @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
p @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
s @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
(anonymous) @ dash_renderer.min.js:2
ku @ dash_renderer.min.js:2
a @ dash_renderer.min.js:2



﻿
react-dom.production.min.js:125 Error: The target 'image_EORTCQLQC29_Q48__1' could not be identified in the dom, tip: check spelling
    at B (dash_bootstrap_compo…nts.min.js:31:67362)
    at W (dash_bootstrap_compo…nts.min.js:31:67570)
    at n.updateTarget (dash_bootstrap_compo…ts.min.js:31:224892)
    at n.componentDidMount (dash_bootstrap_compo…ts.min.js:31:221204)
    at oj (react-dom.production.min.js:127:59)
    at Aj (react-dom.production.min.js:160:448)
    at unstable_runWithPriority (react.production.min.js:25:260)
    at Da (react-dom.production.min.js:60:280)
    at ab (react-dom.production.min.js:154:190)
    at Te (react-dom.production.min.js:146:355)
dash_renderer.min.js:2 Error: The target 'image_EORTCQLQC29_Q48__1' could not be identified in the dom, tip: check spelling
    at B (dash_bootstrap_compo…nts.min.js:31:67362)
    at W (dash_bootstrap_compo…nts.min.js:31:67570)
    at n.updateTarget (dash_bootstrap_compo…ts.min.js:31:224892)
    at n.componentDidMount (dash_bootstrap_compo…ts.min.js:31:221204)
    at oj (react-dom.production.min.js:127:59)
    at Aj (react-dom.production.min.js:160:448)
    at unstable_runWithPriority (react.production.min.js:25:260)
    at Da (react-dom.production.min.js:60:280)
    at ab (react-dom.production.min.js:154:190)
    at Te (react-dom.production.min.js:146:355)
react-dom.production.min.js:125 Error: The target 'image_EORTCQLQC29_Q48__1' could not be identified in the dom, tip: check spelling
    at B (dash_bootstrap_compo…nts.min.js:31:67362)
    at W (dash_bootstrap_compo…nts.min.js:31:67570)
    at n.updateTarget (dash_bootstrap_compo…ts.min.js:31:224892)
    at n.componentDidMount (dash_bootstrap_compo…ts.min.js:31:221204)
    at oj (react-dom.production.min.js:127:59)
    at Aj (react-dom.production.min.js:160:448)
    at unstable_runWithPriority (react.production.min.js:25:260)
    at Da (react-dom.production.min.js:60:280)
    at ab (react-dom.production.min.js:154:190)
    at Te (react-dom.production.min.js:146:355)
dash_renderer.min.js:2 Error: The target 'image_EORTCQLQC29_Q48__1' could not be identified in the dom, tip: check spelling
    at B (dash_bootstrap_compo…nts.min.js:31:67362)
    at W (dash_bootstrap_compo…nts.min.js:31:67570)
    at n.updateTarget (dash_bootstrap_compo…ts.min.js:31:224892)
    at n.componentDidMount (dash_bootstrap_compo…ts.min.js:31:221204)
    at oj (react-dom.production.min.js:127:59)
    at Aj (react-dom.production.min.js:160:448)
    at unstable_runWithPriority (react.production.min.js:25:260)
    at Da (react-dom.production.min.js:60:280)
    at ab (react-dom.production.min.js:154:190)
    at Te (react-dom.production.min.js:146:355)
react-dom.production.min.js:125 Error: The target 'image_EORTCQLQC29_Q48__1' could not be identified in the dom, tip: check spelling
    at B (dash_bootstrap_compo…nts.min.js:31:67362)
    at W (dash_bootstrap_compo…nts.min.js:31:67570)
    at n.updateTarget (dash_bootstrap_compo…ts.min.js:31:224892)
    at n.componentDidMount (dash_bootstrap_compo…ts.min.js:31:221204)
    at oj (react-dom.production.min.js:127:59)
    at Aj (react-dom.production.min.js:160:448)
    at unstable_runWithPriority (react.production.min.js:25:260)
    at Da (react-dom.production.min.js:60:280)
    at ab (react-dom.production.min.js:154:190)
    at Te (react-dom.production.min.js:146:355)
dash_renderer.min.js:2 Error: The target 'image_EORTCQLQC29_Q48__1' could not be identified in the dom, tip: check spelling
    at B (dash_bootstrap_compo…nts.min.js:31:67362)
    at W (dash_bootstrap_compo…nts.min.js:31:67570)
    at n.updateTarget (dash_bootstrap_compo…ts.min.js:31:224892)
    at n.componentDidMount (dash_bootstrap_compo…ts.min.js:31:221204)
    at oj (react-dom.production.min.js:127:59)
    at Aj (react-dom.production.min.js:160:448)
    at unstable_runWithPriority (react.production.min.js:25:260)
    at Da (react-dom.production.min.js:60:280)
    at ab (react-dom.production.min.js:154:190)
    at Te (react-dom.production.min.js:146:355)
react-dom.production.min.js:125 Error: The target 'image_EORTCQLQC29_Q48__1' could not be identified in the dom, tip: check spelling
    at B (dash_bootstrap_compo…nts.min.js:31:67362)
    at W (dash_bootstrap_compo…nts.min.js:31:67570)
    at n.updateTarget (dash_bootstrap_compo…ts.min.js:31:224892)
    at n.componentDidMount (dash_bootstrap_compo…ts.min.js:31:221204)
    at oj (react-dom.production.min.js:127:59)
    at Aj (react-dom.production.min.js:160:448)
    at unstable_runWithPriority (react.production.min.js:25:260)
    at Da (react-dom.production.min.js:60:280)
    at ab (react-dom.production.min.js:154:190)
    at Te (react-dom.production.min.js:146:355)
dash_renderer.min.js:2 Error: The target 'image_EORTCQLQC29_Q48__1' could not be identified in the dom, tip: check spelling
    at B (dash_bootstrap_compo…nts.min.js:31:67362)
    at W (dash_bootstrap_compo…nts.min.js:31:67570)
    at n.updateTarget (dash_bootstrap_compo…ts.min.js:31:224892)
    at n.componentDidMount (dash_bootstrap_compo…ts.min.js:31:221204)
    at oj (react-dom.production.min.js:127:59)
    at Aj (react-dom.production.min.js:160:448)
    at unstable_runWithPriority (react.production.min.js:25:260)
    at Da (react-dom.production.min.js:60:280)
    at ab (react-dom.production.min.js:154:190)
    at Te (react-dom.production.min.js:146:355)

**Comment by id2359** [comment]
This is actually a problem in the code that creates a mouseover element 



The bug is a side effect or the Yes/No field - the circle images act as regions where a mouseover caused a popup. But the english text isn't such a region and causes issues in the React code ( which Dash generates)
