### ISSUE TITLE
runtime error when loading visualisation base data config for Lung cancer 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2447]
Locally,

Deleted everything as a fresh start
Imported staging Lung cancer 
Added one test patient.
In shell,
issued 
django-admin generate_visualisation_dataframe

23-04-05 15:51:14.564934 visualisation base data config: generating json data for ICHOMLC
[INFO:2023-04-05 15:51:14,565:data.py:83:__init__] forcing reload of dataframe..
[INFO:2023-04-05 15:51:14,572:data.py:97:__init__] time taken to load/generate df = 0.007025 seconds
Traceback (most recent call last):
  File "/env/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/rdrf/rdrf/management/commands/generate_visualisation_dataframe.py", line 18, in handle
    json_data = rdf.data.to_json()
AttributeError: 'NoneType' object has no attribute 'to_json'

**Comment by id2359** [comment]
This is caused because no data exists in the clinical data records yet

**Comment by id2359** [comment]
printed  message if this fails.
Data needs to be entered into the data records to create a valid dataframe
