### ISSUE TITLE
Sanity check causes error on staging BC

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#2454]
years3-10 followup has seq 0

```
Name: COLLECTIONDATE, Length: 63, dtype: datetime64[ns]
[INFO:2023-04-17 13:51:01,634:proms_stats.py:12:log] patient_stats: start_date = 2020-05-22 00:00:00
[INFO:2023-04-17 13:51:01,634:proms_stats.py:12:log] patient_stats: end_date = 2023-04-17 13:51:01.634044
[INFO:2023-04-17 13:51:01,636:proms_stats.py:12:log] patient_stats: n = 7
[INFO:2023-04-17 13:51:15,184:dash_apps.py:71:render_tab_content] active tab tab_8
[INFO:2023-04-17 13:51:15,272:data.py:103:__init__] time taken to load/generate df = 0.067663 seconds
[INFO:2023-04-17 13:51:15,907:data.py:88:__init__] loading dataframe from base config json
[INFO:2023-04-17 13:51:16,102:data.py:103:__init__] time taken to load/generate df = 0.19513 seconds
[ERROR:2023-04-17 13:51:16,616:log.py:224:log_response] Internal Server Error: /cicbreast/dash/app/SinglePatientDashboardApp/_dash-update-component
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 700, in dispatch_with_args
    res = callback(*args, **argMap)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/env/lib/python3.8/site-packages/dashboards/dash_apps.py", line 87, in render_tab_content
    graphics_map = get_single_patient_graphics_map(
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 230, in get_single_patient_graphics_map
    graphics_map = {
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 231, in <dictcomp>
    f"tab_{vc.id}": create_graphic(vc, data, patient, None, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 138, in wrapper
    return func(vis_config, data, patient, all_patients_data, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 175, in create_graphic
    return ScaleGroupComparison(
  File "/env/lib/python3.8/site-packages/dashboards/components/common.py", line 58, in graphic
    return self.get_graphic()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 95, in get_graphic
    self.load_all_patients_data()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 524, in load_all_patients_data
    sanity_check("in load all", self.all_patients_data)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 284, in sanity_check
    raise DataFrameError(
dashboards.utils.DataFrameError: in load all followup should have seq > 0: FUpPROMS3_10Years has seq = 0
[INFO:2023-04-17 13:51:20,953:dash_apps.py:71:render_tab_content] active tab tab_7
[INFO:2023-04-17 13:51:21,049:data.py:103:__init__] time taken to load/generate df = 0.071791 seconds
[INFO:2023-04-17 13:51:21,726:data.py:88:__init__] loading dataframe from base config json
[INFO:2023-04-17 13:51:21,923:data.py:103:__init__] time taken to load/generate df = 0.197198 seconds
[ERROR:2023-04-17 13:51:22,427:log.py:224:log_response] Internal Server Error: /cicbreast/dash/app/SinglePatientDashboardApp/_dash-update-component
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 700, in dispatch_with_args
    res = callback(*args, **argMap)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/env/lib/python3.8/site-packages/dashboards/dash_apps.py", line 87, in render_tab_content
    graphics_map = get_single_patient_graphics_map(
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 230, in get_single_patient_graphics_map
    graphics_map = {
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 231, in <dictcomp>
    f"tab_{vc.id}": create_graphic(vc, data, patient, None, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 138, in wrapper
    return func(vis_config, data, patient, all_patients_data, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 175, in create_graphic
    return ScaleGroupComparison(
  File "/env/lib/python3.8/site-packages/dashboards/components/common.py", line 58, in graphic
    return self.get_graphic()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 95, in get_graphic
    self.load_all_patients_data()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 524, in load_all_patients_data
    sanity_check("in load all", self.all_patients_data)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 284, in sanity_check
    raise DataFrameError(
dashboards.utils.DataFrameError: in load all followup should have seq > 0: FUpPROMS3_10Years has seq = 0
[INFO:2023-04-17 13:52:15,191:dash_apps.py:71:render_tab_content] active tab tab_2
[INFO:2023-04-17 13:52:15,279:data.py:103:__init__] time taken to load/generate df = 0.068048 seconds
[INFO:2023-04-17 13:52:15,922:data.py:88:__init__] loading dataframe from base config json
[INFO:2023-04-17 13:52:16,115:data.py:103:__init__] time taken to load/generate df = 0.192276 seconds
[ERROR:2023-04-17 13:52:16,625:log.py:224:log_response] Internal Server Error: /cicbreast/dash/app/SinglePatientDashboardApp/_dash-update-component
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 700, in dispatch_with_args
    res = callback(*args, **argMap)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/env/lib/python3.8/site-packages/dashboards/dash_apps.py", line 87, in render_tab_content
    graphics_map = get_single_patient_graphics_map(
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 230, in get_single_patient_graphics_map
    graphics_map = {
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 231, in <dictcomp>
    f"tab_{vc.id}": create_graphic(vc, data, patient, None, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 138, in wrapper
    return func(vis_config, data, patient, all_patients_data, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 175, in create_graphic
    return ScaleGroupComparison(
  File "/env/lib/python3.8/site-packages/dashboards/components/common.py", line 58, in graphic
    return self.get_graphic()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 95, in get_graphic
    self.load_all_patients_data()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 524, in load_all_patients_data
    sanity_check("in load all", self.all_patients_data)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 284, in sanity_check
    raise DataFrameError(
dashboards.utils.DataFrameError: in load all followup should have seq > 0: FUpPROMS3_10Years has seq = 0
[INFO:2023-04-17 13:52:27,513:dash_apps.py:71:render_tab_content] active tab tab_1
[INFO:2023-04-17 13:52:27,604:data.py:103:__init__] time taken to load/generate df = 0.067605 seconds
[INFO:2023-04-17 13:52:28,236:data.py:88:__init__] loading dataframe from base config json
[INFO:2023-04-17 13:52:28,426:data.py:103:__init__] time taken to load/generate df = 0.190389 seconds
[ERROR:2023-04-17 13:52:28,932:log.py:224:log_response] Internal Server Error: /cicbreast/dash/app/SinglePatientDashboardApp/_dash-update-component
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 700, in dispatch_with_args
    res = callback(*args, **argMap)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/env/lib/python3.8/site-packages/dashboards/dash_apps.py", line 87, in render_tab_content
    graphics_map = get_single_patient_graphics_map(
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 230, in get_single_patient_graphics_map
    graphics_map = {
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 231, in <dictcomp>
    f"tab_{vc.id}": create_graphic(vc, data, patient, None, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 138, in wrapper
    return func(vis_config, data, patient, all_patients_data, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 175, in create_graphic
    return ScaleGroupComparison(
  File "/env/lib/python3.8/site-packages/dashboards/components/common.py", line 58, in graphic
    return self.get_graphic()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 95, in get_graphic
    self.load_all_patients_data()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 524, in load_all_patients_data
    sanity_check("in load all", self.all_patients_data)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 284, in sanity_check
    raise DataFrameError(
dashboards.utils.DataFrameError: in load all followup should have seq > 0: FUpPROMS3_10Years has seq = 0
[INFO:2023-04-17 13:53:05,243:dash_apps.py:71:render_tab_content] active tab tab_6
[INFO:2023-04-17 13:53:05,332:data.py:103:__init__] time taken to load/generate df = 0.068183 seconds
[INFO:2023-04-17 13:53:05,977:data.py:88:__init__] loading dataframe from base config json
[INFO:2023-04-17 13:53:06,172:data.py:103:__init__] time taken to load/generate df = 0.195398 seconds
[ERROR:2023-04-17 13:53:06,686:log.py:224:log_response] Internal Server Error: /cicbreast/dash/app/SinglePatientDashboardApp/_dash-update-component
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 700, in dispatch_with_args
    res = callback(*args, **argMap)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/env/lib/python3.8/site-packages/dashboards/dash_apps.py", line 87, in render_tab_content
    graphics_map = get_single_patient_graphics_map(
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 230, in get_single_patient_graphics_map
    graphics_map = {
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 231, in <dictcomp>
    f"tab_{vc.id}": create_graphic(vc, data, patient, None, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 138, in wrapper
    return func(vis_config, data, patient, all_patients_data, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 175, in create_graphic
    return ScaleGroupComparison(
  File "/env/lib/python3.8/site-packages/dashboards/components/common.py", line 58, in graphic
    return self.get_graphic()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 95, in get_graphic
    self.load_all_patients_data()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 524, in load_all_patients_data
    sanity_check("in load all", self.all_patients_data)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 284, in sanity_check
    raise DataFrameError(
dashboards.utils.DataFrameError: in load all followup should have seq > 0: FUpPROMS3_10Years has seq = 0
[INFO:2023-04-17 13:53:16,983:dash_apps.py:71:render_tab_content] active tab tab_8
[INFO:2023-04-17 13:53:17,075:data.py:103:__init__] time taken to load/generate df = 0.068261 seconds
[ERROR:2023-04-17 13:53:18,207:log.py:224:log_response] Internal Server Error: /cicbreast/dash/app/SinglePatientDashboardApp/_dash-update-component
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 700, in dispatch_with_args
    res = callback(*args, **argMap)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/env/lib/python3.8/site-packages/dashboards/dash_apps.py", line 87, in render_tab_content
    graphics_map = get_single_patient_graphics_map(
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 230, in get_single_patient_graphics_map
    graphics_map = {
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 231, in <dictcomp>
    f"tab_{vc.id}": create_graphic(vc, data, patient, None, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 138, in wrapper
    return func(vis_config, data, patient, all_patients_data, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 175, in create_graphic
    return ScaleGroupComparison(
  File "/env/lib/python3.8/site-packages/dashboards/components/common.py", line 58, in graphic
    return self.get_graphic()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 53, in get_graphic
    sanity_check("in get_graphic", data)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 284, in sanity_check
    raise DataFrameError(
dashboards.utils.DataFrameError: in get_graphic followup should have seq > 0: FUpPROMS3_10Years has seq = 0
[INFO:2023-04-17 13:53:18,264:dash_apps.py:71:render_tab_content] active tab tab_7
[INFO:2023-04-17 13:53:18,356:data.py:103:__init__] time taken to load/generate df = 0.067598 seconds
[ERROR:2023-04-17 13:53:19,440:log.py:224:log_response] Internal Server Error: /cicbreast/dash/app/SinglePatientDashboardApp/_dash-update-component
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 700, in dispatch_with_args
    res = callback(*args, **argMap)
  File "/env/lib/python3.8/site-packages/django_plotly_dash/_callback.py", line 82, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/env/lib/python3.8/site-packages/dashboards/dash_apps.py", line 87, in render_tab_content
    graphics_map = get_single_patient_graphics_map(
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 230, in get_single_patient_graphics_map
    graphics_map = {
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 231, in <dictcomp>
    f"tab_{vc.id}": create_graphic(vc, data, patient, None, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 138, in wrapper
    return func(vis_config, data, patient, all_patients_data, static_followups)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 175, in create_graphic
    return ScaleGroupComparison(
  File "/env/lib/python3.8/site-packages/dashboards/components/common.py", line 58, in graphic
    return self.get_graphic()
  File "/env/lib/python3.8/site-packages/dashboards/components/sgc.py", line 53, in get_graphic
    sanity_check("in get_graphic", data)
  File "/env/lib/python3.8/site-packages/dashboards/utils.py", line 284, in sanity_check
    raise DataFrameError(
dashboards.utils.DataFrameError: in get_graphic followup should have seq > 0: FUpPROMS3_10Years has seq = 0

```

**Comment by id2359** [comment]
a baseline was after the followups
