### ISSUE TITLE
explorer download error

### ISSUE THREAD

**Issue by aahunter** [muccg/rdrf#313]
[ERROR:2016-11-02 11:44:18,256:exception.py:124:handle_uncaught_exception] Internal Server Error: /ophg/explorer/query/download/10/download
Traceback (most recent call last):
  File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/env/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/env/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/env/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/rdrf/explorer/views.py", line 38, in dispatch
    request, *args, **kwargs)
  File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/rdrf/explorer/views.py", line 239, in get
    return self._spreadsheet(query_model)
  File "/app/rdrf/explorer/views.py", line 204, in _spreadsheet
    response = HttpResponse(FileWrapper(output), content_type='application/excel')
  File "/env/lib/python3.5/site-packages/django/http/response.py", line 293, in __init__
    self.content = content
  File "/env/lib/python3.5/site-packages/django/http/response.py", line 319, in content
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/env/lib/python3.5/site-packages/django/http/response.py", line 319, in <genexpr>
    content = b''.join(self.make_bytes(chunk) for chunk in value)
  File "/usr/local/lib/python3.5/wsgiref/util.py", line 30, in __next__
    data = self.filelike.read(self.blksize)
  File "/usr/local/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 10: invalid start byte

**Comment by aahunter** [comment]
https://github.com/muccg/rdrf/commit/359234b7f03756075b3101d8a6ffaef06e36001b
