### ISSUE TITLE
Key error on save patient demographics ID

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#320]
on modjgo branch

builtins.KeyError
KeyError: '_id'

Traceback (most recent call last)
File "/env/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
return self.application(environ, start_response)
File "/env/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
response = self.get_response(request)
File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response
response = self._middleware_chain(request)
File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
response = response_for_exception(request, exc)
File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 86, in response_for_exception
response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 128, in handle_uncaught_exception
return debug.technical_500_response(request, *exc_info)
File "/env/lib/python3.5/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
six.reraise(exc_type, exc_value, tb)
File "/env/lib/python3.5/site-packages/six.py", line 686, in reraise
raise value
File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
response = get_response(request)
File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
response = self._get_response(request)
File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
return self.dispatch(request, *args, **kwargs)
File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
return handler(request, *args, **kwargs)
File "/app/rdrf/rdrf/patient_view.py", line 573, in get
patient_id, registry_code, request)
File "/app/rdrf/rdrf/patient_view.py", line 822, in _get_patient_and_forms_sections
instance=patient, user=user, registry_model=registry)
File "/app/rdrf/registry/patients/admin_forms.py", line 179, in __init__
registry_specific_data = self._get_registry_specific_data(instance)
File "/app/rdrf/registry/patients/admin_forms.py", line 251, in _get_registry_specific_data
return mongo_wrapper.load_registry_specific_data(self.registry_model)
File "/app/rdrf/rdrf/dynamic_data.py", line 543, in load_registry_specific_data
del registry_data[k]
KeyError: '_id'

**Comment by id2359** [comment]
This is because FH has custom behaviour on patient demographics

**Comment by id2359** [comment]
I've fixed this in modjgo-lee branch
