### ISSUE TITLE
fh custom field file save form error (modjgo branch)

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#321]
builtins.TypeError
TypeError: 'form' is an invalid keyword argument for this function

Traceback (most recent call last)
File "/env/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
return self.application(environ, start_response)
File "/env/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
response = self.get_response(request)
File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response
response = self._middleware_chain(request)
File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
response = response_for_exception(request, exc)
File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 86, in response_for_exception
response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 128, in handle_uncaught_exception
return debug.technical_500_response(request, *exc_info)
File "/env/lib/python3.5/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
six.reraise(exc_type, exc_value, tb)
File "/env/lib/python3.5/site-packages/six.py", line 686, in reraise
raise value
File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
response = get_response(request)
File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
response = self._get_response(request)
File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
return self.dispatch(request, *args, **kwargs)
File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
return handler(request, *args, **kwargs)
File "/app/rdrf/rdrf/patient_view.py", line 703, in post
registry_specific_fields_handler.save_registry_specific_data_in_mongo(request)
File "/app/rdrf/rdrf/registry_specific_fields.py", line 53, in save_registry_specific_data_in_mongo
processed_value = self._process_file_cde_value(cde_model, form_value)
File "/app/rdrf/rdrf/registry_specific_fields.py", line 75, in _process_file_cde_value
Display the sourcecode for this frameOpen an interactive python shell in this frameself.registry_model, file_cde_model, form_value)
File "/app/rdrf/rdrf/filestorage.py", line 37, in store_file
item=file_obj, filename=file_obj.name)
File "/env/lib/python3.5/site-packages/django/db/models/base.py", line 555, in __init__
raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'form' is an invalid keyword argument for this function
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by id2359** [comment]
I'll fix this in modjgo-lee if I can

**Comment by id2359** [comment]
fixed on modjgo-lee
