### ISSUE TITLE
500 error clicking the "History"  clock icon to the left of a field

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#394]
The "View Previous Values" popup no longer works

The javascript console shows a 500 error has occurred on the server

**Comment by id2359** [comment]
From registry.log:

[ERROR:2017-02-14 10:23:17,460:exception.py:124:handle_uncaught_exception] Internal Server Error: /fh/forms/12/3/fhDateSection/4/FHconsentDate/history
Traceback (most recent call last):
  File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/env/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/env/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/env/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/rdrf/rdrf/form_view.py", line 795, in get
    return super(FormFieldHistoryView, self).get(request, **kwargs)
  File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 155, in get
    context = self.get_context_data(**kwargs)
  File "/app/rdrf/rdrf/form_view.py", line 810, in get_context_data
    section_code, cde_code)
  File "/app/rdrf/rdrf/dynamic_data.py", line 479, in get_cde_val
    return data.cde_val(form_name, section_code, cde_code)
AttributeError: 'ModjgoQuerySet' object has no attribute 'cde_val'
[INFO:2017-02-14 10:23:17,537:_internal.py:87:_log] 172.19.0.1 - - [14/Feb/2017 10:23:17] "GET /fh/forms/12/3/fhDateSection/4/FHconsentDate/history HTTP/1.1" 500 -

**Comment by id2359** [comment]
This has been fixed already - probably by fixing something else that broke the original javascript - but no explicit commit message refereing this ticket is in git.
