### ISSUE TITLE
TypeError: unorderable types: NoneType() < NoneType() when sorting diagnosis entry progress when no data

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#414]
TypeError: unorderable types: NoneType() < NoneType()

**Comment by id2359** [comment]
In Python 2.7
>>> sorted([10,9,None,5])
[None, 5, 9, 10]
>>> sorted([None,None,None])
[None, None, None]

in Python 3.5
>>> sorted([10,9,None,5])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: NoneType() < int()

>>> sorted([None,None,None])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: NoneType() < NoneType()

**Comment by id2359** [comment]
fixed lee branch
