### ISSUE TITLE
Error loading patient listing for Gaucher staging

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#547]
```
[ERROR:2017-12-05 15:07:51,044:exception.py:124:handle_uncaught_exception] Internal Server Error: /gaucher/patientslisting
Traceback (most recent call last):
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'FormWrapper' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/rdrf/rdrf/patients_listing.py", line 136, in post
    rows = self.get_results(request)
  File "/app/rdrf/rdrf/patients_listing.py", line 178, in get_results
    patients = self.run_query()
  File "/app/rdrf/rdrf/patients_listing.py", line 218, in run_query
    return self.get_rows_in_page()
  File "/app/rdrf/rdrf/patients_listing.py", line 258, in get_rows_in_page
    self.append_rows(page, rows)
  File "/app/rdrf/rdrf/patients_listing.py", line 263, in append_rows
    row_list_to_update.append(self._get_row_dict(obj))
  File "/app/rdrf/rdrf/patients_listing.py", line 270, in _get_row_dict
    for col in self.columns}
  File "/app/rdrf/rdrf/patients_listing.py", line 270, in <dictcomp>
    for col in self.columns}
  File "/app/rdrf/rdrf/patients_listing.py", line 479, in cell
    return "".join(self._get_forms_buttons(patient))
  File "/app/rdrf/rdrf/patients_listing.py", line 484, in _get_forms_buttons
    return [self._get_forms_button(patient, None, self.free_forms)]
  File "/app/rdrf/rdrf/patients_listing.py", line 512, in _get_forms_button
    """ % (button.id, button.button_caption, button.id, button.html)
  File "/app/rdrf/rdrf/components.py", line 55, in html
    return self._fill_template()
  File "/app/rdrf/rdrf/components.py", line 64, in _fill_template
    return template.render(context)
  File "/env/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/env/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 1044, in render
    output = self.filter_expression.resolve(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 711, in resolve
    obj = self.var.resolve(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 852, in resolve
    value = self._resolve_lookup(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "/app/rdrf/rdrf/components.py", line 297, in link
    self.context_model.id))
AttributeError: 'NoneType' object has no attribute 'id'
Internal Server Error: /gaucher/patientslisting
Traceback (most recent call last):
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'FormWrapper' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/rdrf/rdrf/patients_listing.py", line 136, in post
    rows = self.get_results(request)
  File "/app/rdrf/rdrf/patients_listing.py", line 178, in get_results
    patients = self.run_query()
  File "/app/rdrf/rdrf/patients_listing.py", line 218, in run_query
    return self.get_rows_in_page()
  File "/app/rdrf/rdrf/patients_listing.py", line 258, in get_rows_in_page
    self.append_rows(page, rows)
  File "/app/rdrf/rdrf/patients_listing.py", line 263, in append_rows
    row_list_to_update.append(self._get_row_dict(obj))
  File "/app/rdrf/rdrf/patients_listing.py", line 270, in _get_row_dict
    for col in self.columns}
  File "/app/rdrf/rdrf/patients_listing.py", line 270, in <dictcomp>
    for col in self.columns}
  File "/app/rdrf/rdrf/patients_listing.py", line 479, in cell
    return "".join(self._get_forms_buttons(patient))
  File "/app/rdrf/rdrf/patients_listing.py", line 484, in _get_forms_buttons
    return [self._get_forms_button(patient, None, self.free_forms)]
  File "/app/rdrf/rdrf/patients_listing.py", line 512, in _get_forms_button
    """ % (button.id, button.button_caption, button.id, button.html)
  File "/app/rdrf/rdrf/components.py", line 55, in html
    return self._fill_template()
  File "/app/rdrf/rdrf/components.py", line 64, in _fill_template
    return template.render(context)
  File "/env/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/env/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 1044, in render
    output = self.filter_expression.resolve(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 711, in resolve
    obj = self.var.resolve(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 852, in resolve
    value = self._resolve_lookup(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "/app/rdrf/rdrf/components.py", line 297, in link
    self.context_model.id))
AttributeError: 'NoneType' object has no attribute 'id'
[ERROR:2017-12-05 15:07:51,054:exception.py:124:handle_uncaught_exception] Internal Server Error: /gaucher/patientslisting
Traceback (most recent call last):
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'FormWrapper' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/env/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/rdrf/rdrf/patients_listing.py", line 136, in post
    rows = self.get_results(request)
  File "/app/rdrf/rdrf/patients_listing.py", line 178, in get_results
    patients = self.run_query()
  File "/app/rdrf/rdrf/patients_listing.py", line 218, in run_query
    return self.get_rows_in_page()
  File "/app/rdrf/rdrf/patients_listing.py", line 258, in get_rows_in_page
    self.append_rows(page, rows)
  File "/app/rdrf/rdrf/patients_listing.py", line 263, in append_rows
    row_list_to_update.append(self._get_row_dict(obj))
  File "/app/rdrf/rdrf/patients_listing.py", line 270, in _get_row_dict
    for col in self.columns}
  File "/app/rdrf/rdrf/patients_listing.py", line 270, in <dictcomp>
    for col in self.columns}
  File "/app/rdrf/rdrf/patients_listing.py", line 479, in cell
    return "".join(self._get_forms_buttons(patient))
  File "/app/rdrf/rdrf/patients_listing.py", line 484, in _get_forms_buttons
    return [self._get_forms_button(patient, None, self.free_forms)]
  File "/app/rdrf/rdrf/patients_listing.py", line 512, in _get_forms_button
    """ % (button.id, button.button_caption, button.id, button.html)
  File "/app/rdrf/rdrf/components.py", line 55, in html
    return self._fill_template()
  File "/app/rdrf/rdrf/components.py", line 64, in _fill_template
    return template.render(context)
  File "/env/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/env/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 1044, in render
    output = self.filter_expression.resolve(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 711, in resolve
    obj = self.var.resolve(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 852, in resolve
    value = self._resolve_lookup(context)
  File "/env/lib/python3.5/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "/app/rdrf/rdrf/components.py", line 297, in link
    self.context_model.id))
AttributeError: 'NoneType' object has no attribute 'id'
[pid: 35|app: 0|req: 27/1288] 10.0.0.45 () {62 vars in 1597 bytes} [Tue Dec  5 15:07:50 2017] POST /gaucher/patientslisting?registry_code=GR&length=10&context_form_group_id= => generated 21808 bytes in 419 msecs (HTTP/1.1 500) 6 headers in 206 bytes (1 switches on core 0)
[pid: 35|app: 0|req: 27/1289] 10.0.0.45 () {62 vars in 1597 bytes} [Tue Dec  5 15:07:50 2017] POST /gaucher/patientslisting?registry_code=GR&length=10&context_form_group_id= => generated 21808 bytes in 423 msecs (HTTP/1.1 500) 6 headers in 206 bytes (1 switches on core 1)
[pid: 38|app: 0|req: 6/1290] 10.0.0.45 () {56 vars in 1110 bytes} [Tue Dec  5 15:08:34 2017] GET /gaucher/login?next=/router/ => generated 5883 bytes in 184 msecs (HTTP/1.1 200) 10 headers in 562 bytes (1 switches on core 0)

```

**Comment by knapier** [comment]
Registry deleted and re imported, context form groups reassigned. Issue solved.
