### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#583]
root@e27f17ffaa7f:~# django-admin import /app/rdrf/rdrf/testing/behaviour/features/exported_data/dd.zip
[INFO:2018-02-23 15:58:20,675:apps.py:13:ready] running RDRFConfig.ready ... 
Traceback (most recent call last):
  File "/env/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/rdrf/rdrf/management/commands/import.py", line 3, in <module>
    from rdrf.services.io.data.export_import import import_zipfile, inspect_zipfile, definitions
  File "/app/rdrf/rdrf/services/io/data/export_import/__init__.py", line 2, in <module>
    from .main_exporters import Exporter, RegistryExporter, RegistryDefExporter
  File "/app/rdrf/rdrf/services/io/data/export_import/main_exporters.py", line 10, in <module>
    from .definitions import REGISTRY_DEF_EXPORT_DEFINITION, REGISTRY_WITH_DATA_EXPORT_DEFINITION
  File "/app/rdrf/rdrf/services/io/data/export_import/definitions.py", line 3, in <module>
    from . import model_exporters, datagroup_exporters
  File "/app/rdrf/rdrf/services/io/data/export_import/model_exporters.py", line 1, in <module>
    from rdrf.models.definitions import models
ModuleNotFoundError: No module named 'rdrf.models.definitions'
root@e27f17ffaa7f:~#

**Comment by id2359** [comment]
Fixed in #582
