### ISSUE TITLE
stellar broken

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#592]
As part of the aloe tests, export files ( like fh.zip) are loaded into a blank site and then backed up to a snapshot using stellar (https://github.com/fastmonkeys/stellar). The stellar commands are currently failing with:
```
10:30:25   Scenario: Add multiple items to a multisection.                                                                     # features/fh_multisection_tests.feature:10
10:30:40     Given export "fh.zip"
10:30:40 
10:30:50 ======================================================================
10:30:50 ERROR: Curator user adds a new patient (features.dd_add_patient: Add a patient)
10:30:50 ----------------------------------------------------------------------
10:30:50 Traceback (most recent call last):
10:30:50   File "/env/lib/python3.6/site-packages/aloe/registry.py", line 161, in wrapped
10:30:50     return function(*args, **kwargs)
10:30:50   File "/app/rdrf/rdrf/testing/behaviour/features/dd_add_patient.feature", line 2, in Curator user adds a new patient
10:30:50     As a RDRF registry owner
10:30:50   File "/app/rdrf/rdrf/testing/behaviour/features/dd_add_patient.feature", line 7, in background
10:30:50     Given export "dd.zip"
10:30:50   File "/env/lib/python3.6/site-packages/aloe/registry.py", line 161, in wrapped
10:30:50     return function(*args, **kwargs)
10:30:50   File "/app/rdrf/rdrf/testing/behaviour/features/steps.py", line 161, in load_export
10:30:50     utils.load_export(export_name)
10:30:50   File "/app/rdrf/rdrf/testing/behaviour/features/utils.py", line 127, in load_export
10:30:50     django_import(export_name)
10:30:50   File "/app/rdrf/rdrf/testing/behaviour/features/utils.py", line 136, in django_import
10:30:50     ["import", "{0}/{1}".format(exported_data_path(), export_name)], fail_on_error=True)
10:30:50   File "/app/rdrf/rdrf/testing/behaviour/features/utils.py", line 161, in django_admin
10:30:50     (' '.join(["django-admin.py"] + args), return_code))
10:30:50 Exception: 'django-admin.py import /app/rdrf/rdrf/testing/behaviour/features/exported_data/dd.zip' command failed with error code 1
10:30:50 -------------------- >> begin captured logging << --------------------
10:30:50 features.terrain: INFO: Scenario: Curator user adds a new patient
10:30:50 selenium.webdriver.remote.remote_connection: DEBUG: DELETE http://172.18.0.2:4444/wd/hub/session/f058c412-ebac-4c61-9362-28d4686d2aff/cookie {"sessionId": "f058c412-ebac-4c61-9362-28d4686d2aff"}
10:30:50 selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
10:30:50 features.utils: INFO: ['stellar', 'list']
10:30:50 features.utils: ERROR: b'Traceback (most recent call last):\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context\n    context)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute\n    cursor.execute(statement, parameters)\npsycopg2.OperationalError: source database "template1" is being accessed by other users\nDETAIL:  There is 1 other session using the database.\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/env/bin/stellar", line 11, in <module>\n    load_entry_point(\'stellar==0.4.4\', \'console_scripts\', \'stellar\')()\n  File "/env/lib/python3.6/site-packages/stellar/command.py", line 279, in main\n    stellar()\n  File "/env/lib/python3.6/site-packages/click/core.py", line 722, in __call__\n    return self.main(*args, **kwargs)\n  File "/env/lib/python3.6/site-packages/click/core.py", line 697, in main\n    rv = self.invoke(ctx)\n  File "/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke\n    return callback(*args, **kwargs)\n  File "/env/lib/python3.6/site-packages/stellar/command.py", line 76, in list\n    snapshots = get_app().get_snapshots()\n  File "/env/lib/python3.6/site-packages/stellar/command.py", line 28, in get_app\n    app = Stellar()\n  File "/env/lib/python3.6/site-packages/stellar/app.py", line 45, in __init__\n    self.init_database()\n  File "/env/lib/python3.6/site-packages/stellar/app.py", line 64, in init_database\n    tables_missing = self.create_stellar_database()\n  File "/env/lib/python3.6/site-packages/stellar/app.py", line 72, in create_stellar_database\n    self.operations.create_database(\'stellar_data\')\n  File "/env/lib/python3.6/site-packages/stellar/operations.py", line 54, in create_database\n    get_engine_url(raw_conn, database)\n  File "/env/lib/python3.6/site-packages/sqlalchemy_utils/functions/database.py", line 554, in create_database\n    result_proxy = engine.execute(text)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1991, in execute\n    return connection.execute(statement, *multiparams, **params)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 906, in execute\n    return self._execute_text(object, multiparams, params)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text\n    statement, parameters\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context\n    context)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception\n    exc_info\n  File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 185, in reraise\n    raise value.with_traceback(tb)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context\n    context)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.OperationalError: (psycopg2.OperationalError) source database "template1" is being accessed by other users\nDETAIL:  There is 1 other session using the database.\n [SQL: "CREATE DATABASE stellar_data ENCODING \'utf8\' TEMPLATE template1"]\n'
10:30:50 features.utils: ERROR: Return code 1
10:30:50 features.utils: ERROR: b'Traceback (most recent call last):\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context\n    context)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute\n    cursor.execute(statement, parameters)\npsycopg2.OperationalError: source database "template1" is being accessed by other users\nDETAIL:  There is 1 other session using the database.\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/env/bin/stellar", line 11, in <module>\n    load_entry_point(\'stellar==0.4.4\', \'console_scripts\', \'stellar\')()\n  File "/env/lib/python3.6/site-packages/stellar/command.py", line 279, in main\n    stellar()\n  File "/env/lib/python3.6/site-packages/click/core.py", line 722, in __call__\n    return self.main(*args, **kwargs)\n  File "/env/lib/python3.6/site-packages/click/core.py", line 697, in main\n    rv = self.invoke(ctx)\n  File "/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke\n    return callback(*args, **kwargs)\n  File "/env/lib/python3.6/site-packages/stellar/command.py", line 76, in list\n    snapshots = get_app().get_snapshots()\n  File "/env/lib/python3.6/site-packages/stellar/command.py", line 28, in get_app\n    app = Stellar()\n  File "/env/lib/python3.6/site-packages/stellar/app.py", line 45, in __init__\n    self.init_database()\n  File "/env/lib/python3.6/site-packages/stellar/app.py", line 64, in init_database\n    tables_missing = self.create_stellar_database()\n  File "/env/lib/python3.6/site-packages/stellar/app.py", line 72, in create_stellar_database\n    self.operations.create_database(\'stellar_data\')\n  File "/env/lib/python3.6/site-packages/stellar/operations.py", line 54, in create_database\n    get_engine_url(raw_conn, database)\n  File "/env/lib/python3.6/site-packages/sqlalchemy_utils/functions/database.py", line 554, in create_database\n    result_proxy = engine.execute(text)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1991, in execute\n    return connection.execute(statement, *multiparams, **params)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 906, in execute\n    return self._execute_text(object, multiparams, params)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text\n    statement, parameters\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context\n    context)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception\n    exc_info\n  File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 185, in reraise\n    raise value.with_traceback(tb)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context\n    context)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.OperationalError: (psycopg2.OperationalError) source database "template1" is being accessed by other users\nDETAIL:  There is 1 other session using the database.\n [SQL: "CREATE DATABASE stellar_data ENCODING \'utf8\' TEMPLATE template1"]\n'
10:30:50 features.utils: ERROR: Return code 1
```

**Comment by id2359** [comment]
```
[ERROR:2018-04-06 15:24:57,945:utils.py:43:subprocess_logging] b'Traceback (most recent call last):\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context\n    context)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute\n    cursor.execute(statement, parameters)\npsycopg2.OperationalError: source database "template1" is being accessed by other users\nDETAIL:  There is 1 other session using the database.\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/env/bin/stellar", line 11, in <module>\n    load_entry_point(\'stellar==0.4.4\', \'console_scripts\', \'stellar\')()\n  File "/env/lib/python3.6/site-packages/stellar/command.py", line 279, in main\n    stellar()\n  File "/env/lib/python3.6/site-packages/click/core.py", line 722, in __call__\n    return self.main(*args, **kwargs)\n  File "/env/lib/python3.6/site-packages/click/core.py", line 697, in main\n    rv = self.invoke(ctx)\n  File "/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke\n    return callback(*args, **kwargs)\n  File "/env/lib/python3.6/site-packages/stellar/command.py", line 76, in list\n    snapshots = get_app().get_snapshots()\n  File "/env/lib/python3.6/site-packages/stellar/command.py", line 28, in get_app\n    app = Stellar()\n  File "/env/lib/python3.6/site-packages/stellar/app.py", line 45, in __init__\n    self.init_database()\n  File "/env/lib/python3.6/site-packages/stellar/app.py", line 64, in init_database\n    tables_missing = self.create_stellar_database()\n  File "/env/lib/python3.6/site-packages/stellar/app.py", line 72, in create_stellar_database\n    self.operations.create_database(\'stellar_data\')\n  File "/env/lib/python3.6/site-packages/stellar/operations.py", line 54, in create_database\n    get_engine_url(raw_conn, database)\n  File "/env/lib/python3.6/site-packages/sqlalchemy_utils/functions/database.py", line 554, in create_database\n    result_proxy = engine.execute(text)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1991, in execute\n    return connection.execute(statement, *multiparams, **params)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 906, in execute\n    return self._execute_text(object, multiparams, params)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text\n    statement, parameters\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context\n    context)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception\n    exc_info\n  File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 185, in reraise\n    raise value.with_traceback(tb)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context\n    context)\n  File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.OperationalError: (psycopg2.OperationalError) source database "template1" is being accessed by other users\nDETAIL:  There is 1 other session using the database.\n [SQL: "CREATE DATABASE stellar_data ENCODING \'utf8\' TEMPLATE template1"]\n'
```

**Comment by id2359** [comment]
Looks like this is the recent update of sqlalchemy-utils (0.33.2 4 days ago)  which stellar uses. pinned our test stack to 0.33.1
