### ISSUE TITLE
Transaction rollback  for registration causes issue

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#615]
I simulated a "bad frontend" which allowed an overlong field element to be passed through.
The transaction block rolls back, but a subsequent user deletion fails:
```
django.db.transaction.TransactionManagementError
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

Traceback (most recent call last)
File "/env/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
return self.application(environ, start_response)
File "/env/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
response = self.get_response(request)
File "/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in get_response
response = self._middleware_chain(request)
File "/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 44, in inner
response = response_for_exception(request, exc)
File "/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
File "/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 136, in handle_uncaught_exception
return debug.technical_500_response(request, *exc_info)
File "/env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
six.reraise(exc_type, exc_value, tb)
File "/env/lib/python3.6/site-packages/six.py", line 686, in reraise
raise value
File "/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
response = get_response(request)
File "/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
response = self._get_response(request)
File "/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
return self.dispatch(request, *args, **kwargs)
File "/env/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
return bound_func(*args, **kwargs)
File "/env/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
return view(request, *args, **kwargs)
File "/env/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
return func.__get__(self, type(self))(*args2, **kwargs2)
File "/env/lib/python3.6/site-packages/registration/views.py", line 39, in dispatch
return super(RegistrationView, self).dispatch(request, *args, **kwargs)
File "/env/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
return handler(request, *args, **kwargs)
File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
return func(*args, **kwds)
File "/app/rdrf/rdrf/rdrf/views/registration_rdrf.py", line 27, in post
return self.form_valid(form)
File "/env/lib/python3.6/site-packages/registration/views.py", line 42, in form_valid
new_user = self.register(form)
File "/env/lib/python3.6/site-packages/registration/backends/default/views.py", line 100, in register
request=self.request)
File "/env/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 191, in send
response = receiver(signal=self, sender=sender, **named)
File "/app/rdrf/rdrf/registry/groups/models.py", line 271, in user_registered_callback
user.delete()
File "/env/lib/python3.6/site-packages/django/db/models/base.py", line 957, in delete
Display the sourcecode for this frameOpen an interactive python shell in this framecollector.collect([self], keep_parents=keep_parents)
File "/env/lib/python3.6/site-packages/django/db/models/deletion.py", line 226, in collect
elif sub_objs:
File "/env/lib/python3.6/site-packages/django/db/models/query.py", line 260, in __bool__
self._fetch_all()
File "/env/lib/python3.6/site-packages/django/db/models/query.py", line 1087, in _fetch_all
self._result_cache = list(self.iterator())
File "/env/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
results = compiler.execute_sql()
File "/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
cursor.execute(sql, params)
File "/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
return super(CursorDebugWrapper, self).execute(sql, params)
File "/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 59, in execute
self.db.validate_no_broken_transaction()
File "/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 428, in validate_no_broken_transaction
"An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

**Comment by id2359** [comment]
This was fixed when I remodelled the registration transaction handling in another ticket
