### ISSUE TITLE
test broken ( followups)

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#712]

**Comment by id2359** [comment]
```

======================================================================
ERROR: Navigate to Follow Up Form (features.fh_add_followup: Follow Up forms.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/aloe/registry.py", line 161, in wrapped
    return function(*args, **kwargs)
  File "/app/rdrf/rdrf/testing/behaviour/features/fh_add_followup.feature", line 12, in Navigate to Follow Up Form
    And I press "Add" button in "Follow Ups" group in sidebar
  File "/env/lib/python3.6/site-packages/aloe/registry.py", line 161, in wrapped
    return function(*args, **kwargs)
  File "/app/rdrf/rdrf/testing/behaviour/features/steps.py", line 218, in click_button_sidebar_group
    group_name).find_element_by_xpath("..")
  File "/env/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 260, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/env/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 508, in find_element
    {"using": by, "value": value})['value']
  File "/env/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 491, in _execute
    return self._parent.execute(command, params)
  File "/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="panel-heading"][contains(., "Follow Ups")]"}
  (Session info: chrome=57.0.2987.110)
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 4.4.0-101-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.05 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.2.0', revision: '8c03df6', time: '2017-03-02 09:34:51 -0800'
System info: host: '36ee9597483b', ip: '172.18.0.8', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-101-generic', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f), userDataDir=/tmp/.org.chromium.Chromium.wnlaHC}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=57.0.2987.110, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: c38e27ec36ad0ecc7599060dee543d0b
*** Element info: {Using=xpath, value=//div[@class="panel-heading"][contains(., "Follow Ups")]}
Screenshot: available via screen
Stacktrace:
    at sun.reflect.NativeConstructorAccessorImpl.newInstanc
```

**Comment by aminur80** [comment]
Duplicate issue - https://github.com/muccg/rdrf/issues/713
