### ISSUE TITLE
Fix errors in test cases while upgrade Django

### ISSUE THREAD

**Issue by aminur80** [muccg/rdrf#718]
Fix errors in test cases while upgrade Django

**Comment by aminur80** [comment]
======================================================================
ERROR: Curator user adds a new patient (features.dd_add_patient: Add a patient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/aloe/registry.py", line 161, in wrapped
    return function(*args, **kwargs)
  File "/app/rdrf/rdrf/testing/behaviour/features/dd_add_patient.feature", line 2, in Curator user adds a new patient
    As a RDRF registry owner
  File "/app/rdrf/rdrf/testing/behaviour/features/dd_add_patient.feature", line 7, in background
    Given export "dd.zip"
  File "/env/lib/python3.6/site-packages/aloe/registry.py", line 161, in wrapped
    return function(*args, **kwargs)
  File "/app/rdrf/rdrf/testing/behaviour/features/steps.py", line 161, in load_export
    utils.load_export(export_name)
  File "/app/rdrf/rdrf/testing/behaviour/features/utils.py", line 127, in load_export
    django_import(export_name)
  File "/app/rdrf/rdrf/testing/behaviour/features/utils.py", line 136, in django_import
    ["import", "{0}/{1}".format(exported_data_path(), export_name)], fail_on_error=True)
  File "/app/rdrf/rdrf/testing/behaviour/features/utils.py", line 161, in django_admin
    (' '.join(["django-admin.py"] + args), return_code))
Exception: 'django-admin.py import /app/rdrf/rdrf/testing/behaviour/features/exported_data/dd.zip' command failed with error code 1
-------------------- >> begin captured logging << --------------------
features.terrain: INFO: Scenario: Curator user adds a new patient
selenium.webdriver.remote.remote_connection: DEBUG: DELETE http://172.18.0.4:4444/wd/hub/session/9ac51031-9bed-489a-8d41-3c9138775980/cookie {"sessionId": "9ac51031-9bed-489a-8d41-3c9138775980"}
selenium.webdriver.remote.remote_connection: DEBUG: Finished Request
features.utils: INFO: ['stellar', 'list']
features.utils: INFO: b'minimal: 2 minutes ago\n'
features.utils: ERROR: b'/env/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.\n  """)\n'
features.utils: INFO: b'minimal: 2 minutes ago\n'
features.utils: ERROR: b'/env/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.\n  """)\n'
features.utils: INFO: ['import', '/app/rdrf/rdrf/testing/behaviour/features/exported_data/dd.zip']
features.utils: ERROR: b'/env/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.\n  """)\nTraceback (most recent call last):\n  File "/env/bin/django-admin.py", line 5, in <module>\n    management.execute_from_command_line()\n  File "/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line\n    utility.execute()\n  File "/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File "/env/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File "/env/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute\n    output = self.handle(*args, **options)\n  File "/app/rdrf/rdrf/management/commands/import.py", line 51, in handle\n    force=force)\n  File "/app/rdrf/rdrf/services/io/content/export_import/__init__.py", line 55, in import_zipfile\n    indented_logs=indented_logs, simulate=simulate, force=force)\n  File "/app/rdrf/rdrf/services/io/content/export_import/main_importers.py", line 116, in do_import\n    importer.do_import()\n  File "/app/rdrf/rdrf/services/io/content/export_import/main_importers.py", line 241, in do_import\n    self.import_datagroups(get_meta_value(self.meta, \'data_groups\'))\n  File "/app/rdrf/rdrf/services/io/content/export_import/main_importers.py", line 181, in import_datagroups\n    self.check_app_schema_versions_match()\n  File "/app/rdrf/rdrf/services/io/content/export_import/importers.py", line 18, in wrapper\n    return checkfn(self, *args, **kwargs)\n  File "/app/rdrf/rdrf/services/io/content/export_import/main_importers.py", line 164, in check_app_schema_versions_match\n    \', \'.join(app_schema_version_different))\nrdrf.services.io.content.export_import.exceptions.ImportError: Schema difference detected between your registry and the export file. App(s) with different schema: patients, rdrf, groups, auth\n'
features.utils: ERROR: Return code 1
